### ISSUE TITLE
Use Models instead of fields defined in various layout?

### ISSUE THREAD

**Issue by matteopoile** [whitecube/nova-flexible-content#102]
Hi,
I would like to know if it could be possible or if will be planned in a future version of the package to use Models instead of fields defined directly in a Layout.
I'm developing a survey and the interface of flexible layout is what I need to avoid user to change resources to add Questions to the Survey.
I'm thinking that I could use custom resolver but I'm not sure.

Have you got some suggestions?

**Comment by Nyratas** [comment]
Hi @matteopoile,

This is the exact use case we took as an example in the [Custom Resolvers](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes) documentation.

Have a nice day!
