### ISSUE TITLE
Nested layouts are returned as array, not as layout.

### ISSUE THREAD

**Issue by chatzisnik** [whitecube/nova-flexible-content#103]
Hi, I have created a Layout called slideshow, in which I have nested a layout called slide under the  $layout->slides attribute.

On my views I would assume that the intended behaviour is to have a layout of name 'slideshow' which would include an array/collection of layouts of name 'slide' when calling $slideshow->slides

I assumed that something like this should work:
```
      @foreach ($slideshow->slides as $slide)
        <li class="uk-flex uk-flex-middle uk-flex-center">
          <img src="{{getPath($slide->image)}}" alt="" uk-cover>
        </li>
      @endforeach
```
So, I ain't sure if that's intended behaviour or a bug but i have the following output when doing a dd on a slideshow layout:
```
Layout {#536 ▼
  #name: "slideshow"
  #key: "ba62013aea1cfb95"
  #_key: null
  #title: "slideshow"
  #fields: Collection {#537 ▶}
  #casts: []
  #dates: []
  #attributes: array:5 [▼
    "navigation_style" => null
    "animations" => null
    "animation_duration" => null
    "has_navigation_overlay" => false
    "slides" => array:2 [▼
      0 => {#484 ▼
        +"layout": "slide"
        +"key": "ddbdf32e21e04fb7"
        +"attributes": {#522 ▼
          +"alt_text": "asdf"
          +"image": "slides/WRutcy5w5gcWk0eQ4XzhW4jvEmP2gpNoh5QswOGK.jpeg"
        }
      }
      1 => {#488 ▼
        +"layout": "slide"
        +"key": "a838a5a9875b526f"
        +"attributes": {#493 ▼
          +"alt_text": "asdf"
          +"image": "slides/ZBHQkayeXkdWFg9qKSTLT5QNKO1C56SgfNkc2Grd.jpeg"
        }
      }
    ]
  ]
  #original: []
  #changes: []
  #dateFormat: null
  #appends: []
  #hidden: []
  #visible: []
}
```
Notice that the slides attribute has an array of objects which are not of class "Layout". I should now run the following to display my slideshow images. 
```
      @foreach ($slideshow->slides as $slide)
        <li class="uk-flex uk-flex-middle uk-flex-center">
          <img src="{{getPath($slide->attributes->image)}}" alt="" uk-cover>
        </li>
      @endforeach
```
Is there something that I am doing wrong when implementing the solution or it's a genuine bug?

**Comment by Nyratas** [comment]
Hi @chatzisnik,

This is the intended behavior. The Layout's `attributes` contain the raw values (exactly as on a model). If you want the `Layout` to return a collection of Layouts instead of the raw array, you should use [`HasFlexible`'s `flexible()` method](https://github.com/whitecube/nova-flexible-content#using-flexible-values-in-views) within an accessor method on your custom layout:

```php 
    public function getSlidesAttribute()
    {
        return $this->flexible('slides', [
            'slide' => \App\Nova\Flexible\Layouts\CustomSlideLayout::class,
        ]);
    }
```

Alternatively, if you're not using a custom layout class for your "Slideshow" layout, you can use the `flexible` method directly in the view:

```blade
@foreach ($slideshow->flexible('slides') as $slide)
    <li class="uk-flex uk-flex-middle uk-flex-center">
        <img src="{{getPath($slide->image)}}" alt="" uk-cover>
    </li>
@endforeach
```

Hope this helps!

**Comment by chatzisnik** [comment]
Hi @Nyratas,

Amazing! Thanks for your comprehensive answer. 

Please let me know if you think that this should be part of the documentation so I can write something up.

**Comment by voidgraphics** [comment]
@chatzisnik Whoops! It definitely seems like [this part](https://github.com/whitecube/nova-flexible-content#using-flexible-values-in-views) from the read me is missing in the full docs. We'd definitely be grateful if you added it, and feel free to tweak it to make it fit better in the full docs or improve it in any way. Thanks!

**Comment by chatzisnik** [comment]
Hi @Nyratas,

Trying to implement the proposed solution, I still don't get the layouts back.

```SlideshowLayout```

```
<?php

namespace App\Nova\Flexible\Layouts;
use Whitecube\NovaFlexibleContent\Flexible;

use Whitecube\NovaFlexibleContent\Layouts\Layout;
use Laravel\Nova\Fields\Heading;

class SlideshowLayout extends Layout
{
    /**
     * The layout's unique identifier
     *
     * @var string
     */
    protected $name = 'slideshow';

    /**
     * The displayed title
     *
     * @var string
     */
    protected $title = 'Slideshow';

    public function getSlidersAttribute()
    {
        return $this->flexible(
            'slides', [
            'slide' => \App\Nova\Flexible\Layouts\SlideLayout::class,
            ]
        );
    }

    /**
     * Get the fields displayed by the layout.
     *
     * @return array
     */

    public function fields()
    {
        return [
            Heading::make('Slides'),

            Flexible::make('Slides', 'slides')
                ->addLayout(\App\Nova\Flexible\Layouts\SlideLayout::class)
                ->button('Add Slide'),
        ];
    }

}

```

```SlideLayout.php```
```
<?php

namespace App\Nova\Flexible\Layouts;

use Whitecube\NovaFlexibleContent\Layouts\Layout;
use Laravel\Nova\Fields\Image;
use Laravel\Nova\Fields\Text;
use App\Nova\Invokables\CompressAndStoreImage;

class SlideLayout extends Layout
{
    /**
     * The layout's unique identifier
     *
     * @var string
     */
    protected $name = 'slide';

    /**
     * The displayed title
     *
     * @var string
     */
    protected $title = 'Slide';

    /**
     * Get the fields displayed by the layout.
     *
     * @return array
     */
    public function fields()
    {
        return [
            Text::make('Alt Text', 'alt_text'),

            Image::make('Image', 'image')
                ->store(new CompressAndStoreImage('image', "slides"))
                ->hideFromIndex(),
        ];
    }

}
```

Still, dumping the slideshow layout shows me:
```
Collection {#534 ▼
  #items: array:3 [▼
    0 => Layout {#536 ▼
      #name: "slideshow"
      #key: "ba62013aea1cfb95"
      #_key: null
      #title: "slideshow"
      #fields: Collection {#537 ▶}
      #casts: []
      #dates: []
      #attributes: array:5 [▼
        "navigation_style" => null
        "animations" => null
        "animation_duration" => null
        "has_navigation_overlay" => false
        "slides" => array:2 [▼
          0 => {#484 ▼
            +"layout": "slide"
            +"key": "ddbdf32e21e04fb7"
            +"attributes": {#522 ▼
              +"alt_text": "asdf"
              +"image": "slides/WRutcy5w5gcWk0eQ4XzhW4jvEmP2gpNoh5QswOGK.jpeg"
            }
          }
          1 => {#488 ▼
            +"layout": "slide"
            +"key": "a838a5a9875b526f"
            +"attributes": {#493 ▼
              +"alt_text": "asdf"
              +"image": "slides/ZBHQkayeXkdWFg9qKSTLT5QNKO1C56SgfNkc2Grd.jpeg"
            }
          }
        ]
      ]
      #original: []
      #changes: []
      #dateFormat: null
      #appends: []
      #hidden: []
      #visible: []
```

Is there something I am doing wrong on that?

**Comment by voidgraphics** [comment]
@chatzisnik Try dumping `$slideshow->slides` instead

**Comment by voidgraphics** [comment]
Tried it myself by copy/pasting your code and it seems to work fine:


![Capture d’écran 2019-10-24 à 13 33 38](https://user-images.githubusercontent.com/9298484/67481871-ffc77380-f662-11e9-9968-f35f0c5c6327.png)

**Comment by chatzisnik** [comment]
Hey @voidgraphics,

Running on:
```
"name": "laravel/framework"
"version": "v6.3.0",
````

If you are running this on a recent version as well, I will have a look on my setup and update this thread if I find something interesting.

**Comment by voidgraphics** [comment]
Yep, works fine on `v6.3.0` for me.

**Comment by voidgraphics** [comment]
I found it. If you notice, when you dump your slideshow layout, you have a base `Layout` class, not an instance of your `SlideshowLayout`, which in turns means that it does not use the `getSlidesAccessor` method.

So, the solution is to use the `HasFlexible` trait like explained above in your model that contains the `slideshow` flexible field, along with the right accessor method.

**Comment by chatzisnik** [comment]
Hey @voidgraphics, 

That was it. In order to get Layout Instances of your Layouts, you have to pass explicitly the Layout Mapping as such:
```
    public function getDetailsAttribute()
    {
        return $this->flexible('details', [
            'wysiwyg' => \App\Nova\Flexible\Layouts\FroalaLayout::class,
            'slideshow' => \App\Nova\Flexible\Layouts\SlideshowLayout::class,
            'accordion' => \App\Nova\Flexible\Layouts\AccordionLayout::class,
            ]
        );
    }
```

Thanks for your help. Will update the documentation with some information around this!
