### ISSUE TITLE
Unable to properly use Datetime field in a dynamically declared layout.

### ISSUE THREAD

**Issue by bredmor** [whitecube/nova-flexible-content#104]
Creating a layout with a Datetime field on any resource and saving a model seems to result in the model being unable to load, returning the error `message: DateTime field must cast to 'datetime' in Eloquent model.`. I saw #14, in which the Datetime field can be used if a layout preset is made - but in situations like my use case, where the resulting database column could be any number of dynamic field elements, a preset can't be used.

Is there any known potential solution to make datetime fields render without using a preset layout?

**Comment by cgarofalo** [comment]
I have the same issue Laravel 5.8, Nova 2.7.1, Nova Flexible Content 0.1.12

**Comment by phlisg** [comment]
Same here. I have to instead use HTML input types to be able to create dates in my layouts.

**Comment by rentist** [comment]
hi guys, i'm not sure if it will fix your problem, but in my case (based on https://github.com/whitecube/nova-flexible-content/issues/14#issuecomment-473268821) :
- i generated a layout using command `php artisan flexible:layout MyLayout`
- put `Datetime::make('My Date Time', 'mydatetime')` in MyLayout.php inside `public function fields()`
- caste datetime in MyLayout.php `protected $casts = ['mydatetime' => 'datetime'];`
- call MyLayout.php from desired resource `Flexible::make('My Flexible Field', 'myflexiblefield')->addLayout(MyLayout::class)`

**Comment by phlisg** [comment]
> `caste datetime in MyLayout.php protected $casts = ['mydatetime' => 'datetime'];`

I didn't get that I should add this in the Layout class when I read that issue. I have now tested it and it works great! Thanks for the the head's up :-)

Although it only works with unnested Flexible Layouts, in nested ones, it doesn't work anymore:

```php

protected $casts = [
  'from' => 'datetime',
  'to' => 'datetime',
];

Flexible::make('Openings')
  ->addLayout('Openings', 'json', [
    Multiselect::make('Jours', 'days'),
    // DateTime Field here works!
    Flexible::make('Hours')
        ->addLayout('Hour', 'json', [
        DateTime::make('From'), // Nope
        DateTime::make('To'), // Nope again
    ])
    ->button('Add more hours')
  ])
  ->button(__('Add more openings'))->hideFromIndex(),
```

**Comment by Nyratas** [comment]
Hi @phlisg,

Sorry for the response delay, again.

The `$casts` should be defined on the layout class containing the `DateTime` field, not on the model. This means you should create [custom layout classes](https://whitecube.github.io/nova-flexible-content/#/?id=custom-layout-classes) for those layouts and cast the values to `datetime` on them.

Hope this helps.

**Comment by phlisg** [comment]
@Nyratas 
I'm not better with delays, sorry about that too haha

Yes, your solution works perfectly, tried it today :) thank you again!

**Comment by Sophal24** [comment]
Hello @Nyratas 
For your suggestion to create custom layout and define $casts in that layout class, I followed and it still doesn't work. May I see the sample?
