### ISSUE TITLE
Images in repeated layout got deleted on update

### ISSUE THREAD

**Issue by millybutter** [whitecube/nova-flexible-content#105]
I have a layout like below in my Flexible field.

```
->addLayout('Image', 'image', [
                    Image::make('Image', 'image')
                        ->disk('public')
                        ->prunable()
                        ->path('/Media/BlogPosts/'.$saveID . '/' . substr(str_shuffle(str_repeat('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', mt_rand(1,10))), 1, 20)),                    
                    Text::make('Link')->nullable(),                    
                    Text::make('Text'), 
                ])
```
And I use it like below.
![image](https://user-images.githubusercontent.com/54661047/68190824-25e8fe00-ffe9-11e9-82cf-624dacf84f02.png)

It works fine when I create the resource but when I do updating and add another layout which is of the same type, the last image uploaded of the same type got deleted.

I think this is because the images are stored in the same folder.
As you can see from my code, I tried to customise the file path by adding random strings but it returns the same path for multiple layout.

Please advice. Thanks.

**Comment by paulbeames** [comment]
Hey @millybutter did you find a solution? I am having the same issue.
