### ISSUE TITLE
Move the confirm delete button

### ISSUE THREAD

**Issue by vayurobins** [whitecube/nova-flexible-content#106]
Hi.
When clicking the trash bin, a little confirm delete/cancel delete button appears in the opposite end of the window. This is very easy to miss. It would be great if it was placed right next to the trash bin somehow.
Please see the attached files for a possible alternative solution. :-)
<img width="1057" alt="Screenshot 2019-11-05 at 20 47 27" src="https://user-images.githubusercontent.com/1386354/68213540-5abb7c00-000e-11ea-973a-024619ebbd38.png">
<img width="400" alt="Screenshot 2019-11-05 at 20 52 38" src="https://user-images.githubusercontent.com/1386354/68213548-5f803000-000e-11ea-8d5b-870144fd9130.png">
`.confirm-message {
    position: absolute;
    overflow: visible;
    top: 98px;
    left: 33px;
    /* right: 38px; */
    /* bottom: 0; */
    width: auto;
    border-radius: 0 4px 4px 0;
    padding: 6px 7px;
    border: 1px solid #B7CAD6;
    border-width: 1px 1px 1px 0;
    background-color: var(--20);
    white-space: nowrap;
}`

**Comment by voidgraphics** [comment]
Interesting, it used to be placed almost where you moved it, except on the left side. Maybe some css changed in Nova, or we merged a PR that moved it without noticing 🤔

Thanks for the heads up

**Comment by Nyratas** [comment]
@voidgraphics is this issue still relevant ? I think we have a modal now ?

**Comment by voidgraphics** [comment]
@Nyratas indeed
