### ISSUE TITLE
Syncing MorphMany Relationship in Custom Resolver

### ISSUE THREAD

**Issue by mdavis1982** [whitecube/nova-flexible-content#118]
I'm using the package to add "Social Profiles" to a "Stockist" model.

I'm storing the social profile data in a separate table, and have a `morphMany()` relationship to the `social_profiles` table. My Social Profiles have:

- `order`
- `type`
- `username`

I'm using a Custom Resolver to do the work of storing and retrieving the data. I also have 4 Layouts (`FaceBookLayout`, `TwitterLayout`, `InstagramLayout` and `LinkedInLayout`) and a single Preset (`SocialProfilePreset`).

I can't work out how to sync my relations in the resolver. Deleting them all and recreating them works fine as in the documentation, but I want to update the ones that already exist.

Here is my Custom Resolver class:

```php
<?php

namespace App\Nova\Flexible\Resolvers;

use Whitecube\NovaFlexibleContent\Value\ResolverInterface;

class SocialProfileResolver implements ResolverInterface
{
    /**
     * Get the field's value.
     */
    public function get($resource, $attribute, $layouts)
    {
        $socialProfiles = $resource->socialProfiles()->orderBy('order')->get();

        return $socialProfiles->map(function ($socialProfile) use ($layouts) {
            $layout = $layouts->find($socialProfile->type);

            if (! $layout) {
                return;
            }

            return $layout->duplicateAndHydrate($socialProfile->id, [
                'type' => $socialProfile->type,
                'username' => $socialProfile->username,
            ]);
        })->filter();
    }

    /**
     * Set the field's value.
     */
    public function set($model, $attribute, $groups)
    {
        $class = get_class($model);

        $class::saved(function ($model) use ($groups) {
            $socialProfiles = $groups->map(function ($group, $index) {
                return [
                    'type' => $group->name(),
                    'username' => $group->getAttribute('username'),
                    'order' => $index,
                ];
            })->toArray();

            $model->socialProfiles()->delete();
            $model->socialProfiles()->createMany($socialProfiles);
        });
    }
}
```

I'm passing in the ID as explained in the documentation in the `duplicateAndHydrate()` call in `get()`. This all works fine and it fills the forms in as required with the correct data.

How do I replace the bottom two lines to sync my relations, rather than deleting them all and recreating them? I can't see a way to get the ID passed in the `duplicateAndHydrate()` call back out in the `set()` method.

Any help would be greatly appreciated!

Thanks :smile:

**Comment by Nyratas** [comment]
Hi @mdavis1982,

Sorry for the delay. I hope you found a solution to your problem.

It seems to me this is more an issue with eloquent and the usage of `sync`, am I right?

If you want to find the corresponding IDs for the social profiles, I guess you should first perform a query that will retrieve those, then try to map them to your flexible data using a common pattern (matching `type` attribute).

```php
    /**
     * Set the field's value.
     */
    public function set($model, $attribute, $groups)
    {
        $class = get_class($model);

        $class::saved(function ($model) use ($groups) {
            $profiles = SocialProfiles::all();
            $socialProfiles = $groups->mapWithKeys(function ($group, $index) use ($profiles) {
                $id = $this->findMatchingSocialProfile($profiles, $group), // This method, which you should define, will return an ID found in the $profiles models
                return [
                    $id => [
                        'type' => $group->name(),
                        'username' => $group->getAttribute('username'),
                        'order' => $index,
                    ]
                ];
            })->toArray();
            // ...
        });
    }
```
I did not test this, but I guess you get the idea ;)

Hope this helps. I'm closing this issue since it is not directly related to nova-flexible-content.

Have a great day!
