### ISSUE TITLE
Computing a FlexibleLayout to Database

### ISSUE THREAD

**Issue by phlisg** [whitecube/nova-flexible-content#120]
I currently develop an import system that converts some JSON to a Laravel model. For that I mock a model and then insert it into database.

Since I am using FlexibleLayout in my project, I mimicked what FlexibleLayout inserts into the database, so it can read it when editing a resource:

```json
[{"key": "sJEWqzYGTMYE7gvR", "layout": "emails", "attributes": {"email": "mail@mail.org"}}]
```

For single, unnested Layouts, this works well, FlexibleLayout manages to read this and display it in Nova.

Now my problem is the following: I have more complex layouts, that nest other FlexibleLayouts:
```php
    // App\Nova\Flexible\Layouts\Entity\EntityPricesLayout

    public function fields()
    {
        return [
            Date::make('Du', 'starts'),
            Date::make('Au', 'ends'),
            Boolean::make('Chaque année', 'every_year'),
            Boolean::make('Toujours ouvert', 'always_open'),

            Flexible::make('Openings')
                ->addLayout('Openings', 'json', [
                    Multiselect::make('Jours', 'days'),
                    Flexible::make('Heures', 'hours')
                        ->addLayout('Heure', 'json', [
                            Text::make('De', 'start'),
                            Text::make('À', 'end'),
                        ])->button('Ajouter des heures'),
                ])
                ->button(__('Ajouter une ouverture'))->hideFromIndex(),
        ];
```

A resulting json would look like: 
```json
[{"key": "spvUoC1vTpZHCmaK", "layout": "schedules", "attributes": [{"ends": "2019-12-31 00:00:00", "starts": "2019-01-01 00:00:00", "openings": [], "every_year": true, "always_open": false}]}]
```

I have a test Resource to see how FlexibleLayout stores data, there are no discrepancies, as otherwise FlexibleLayout would throw errors (I've spent a good amount of time on mimicking all this).

This morning I tried using the `Layout` class, but unfortunately it encodes the Nova fields in json, rather than exporting me a similar to above json string:
```php
// Returning a Layout in a property of my class
$this->rendered = new Layout(string $layoutName, string $layoutName, array $fields, string $this->key, Collection $data->toArray());

// exporting it:
return $this->rendered->jsonSerialize()
```

How can I programmatically create a FlexibleLayout and save it to the db?

**Comment by phlisg** [comment]
Hello,

Any solution to compute a FlexibleLayout from code rather than from UI?

**Comment by Nyratas** [comment]
Hi @phlisg,

Did you take a look at the `toFlexible` method in the [HasFlexible](https://github.com/whitecube/nova-flexible-content/blob/master/src/Concerns/HasFlexible.php) trait ?

It works like this (you can map nested layouts using a mutator on the layout classes) : 

```php
$this->toFlexible($json, [
    'wysiwyg' => \App\Nova\Flexible\Layouts\WysiwygLayout::class,
    'video' => \App\Nova\Flexible\Layouts\VideoLayout::class,
]);
```

This will return a collection of populated layouts you could use to resolve a custom "Flexible" class (extending the original field class) in which you would have modified the original behavior for the `resolve` or `resolveForDisplay` methods (the important thing here is to assign the collection to `$this->value` inside the `Flexible` instance).

**Comment by phlisg** [comment]
Hello @Nyratas 

Thank you for your answer and for your time.

So, I tried these approaches based on your answer:
1. I tried without removing my "layout-mimicking" code, I seem to get something:
```php
/* 
$p is an instance of a class that extends Collection.
The method "model()" allows to retrieve a Model 
pre-populated with data from the Collection.

Model has the HasFlexible trait.
*/

$p->model()->toFlexible($p->model()->content, [
'content' => App\Nova\Flexible\Layouts\Entity\EntityContentLayout::class
]);
/* dump:
 Whitecube\NovaFlexibleContent\Layouts\Collection {#3297
     all: [
       App\Nova\Flexible\Layouts\Entity\EntityContentLayout {#3274},
     ],
   }
*/
```
If I `dd()` the returned value, I can see that it seems to be correctly attributed.

If I do `$p->model()->content = ...` I get this (if I understood correctly when you mentionned `$this->value`):

```php
$p->model()->content = $p->model()->toFlexible($p->model()->content, [
'content' => App\Nova\Flexible\Layouts\Entity\EntityContentLayout::class
])
/* dumps: 
Whitecube\NovaFlexibleContent\Layouts\Collection {#4261
     all: [
       App\Nova\Flexible\Layouts\Entity\EntityContentLayout {#4367},
     ],
   }
*/
$p->model()->content
/* dumps:  [
     [
       "name" => "content",
       "title" => "content",
       "fields" => [],
     ],
   ]
*/
```
So I'm not sure I'm doing this correctly :( Not sure I saw something related to that in the docs.

2. I tried removing my mimicking code, I get this: 
`PHP Notice:  Undefined index: attributes in /var/www/projects/laravel/lausanne/vendor/whitecube/nova-flexible-content/src/Concerns/HasFlexible.php on line 108`

I probably got the wrong approach (point 2) or maybe I'm not that far (point 1).

**Comment by Nyratas** [comment]
The `toFlexible` method does not change `$p->model()->content`'s value, it just returns the parsed value. What I meant when talking about `$this->value` was the `value` attribute on the Flexible field instance. In other words, I was suggesting you create a class that extends our `Flexible` class and that you use that one instead.

But that was before reading your last comment. In my opinion, you could achieve what you're trying to do using a [Custom Resolver Class](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes). Resolver classes are used to alter the way the Flexible field will fetch and store its value. The example in the docs will fetch and store the Flexible value in another database table, but you could build your own `get` and `set` methods that will interact with your specific mocks.

**Comment by phlisg** [comment]
Thanks again :) I looked at how to use a custom Resolver in the past but didn't know where to go with that.

I didn't manage to use the Resolver just yet, not sure how to configure `get()` and `set()` with my setup. 

My current logic flow is as follows:
- Get json from API
- convert it to an instance of a class extending Collection (ie `class Poi extends Collection`)
- that instance prepares a mock of a given Model (ie `class Poi extends Model`)
- during the mocking, for specified fields (content is the easiest) I wish to convert the Collection's field to a Flexible value
- save finalized Model mock and visualize it in Nova

I'll test more tomorrow

**Comment by phlisg** [comment]
Hello :D

Just wanted to share that I found out what my problem was. So, FlexibleContent is in the end happy with reading a custom-made JSON string from DB, one must just be careful of its structure and the `layout names` with each block. Then it works fine!

No need for resolvers :)

Thanks again for your help @Nyratas 
The answer was just in front of my nose haha

**Comment by phlisg** [comment]
Hello @Nyratas !

Revining this old issue.

What would be your simple solution to fill a custom `Layout` class using `setAttribute()` (or something else) and then store it in database?

I'm looking for something that does `$model->setAttribute('attribute', $layout)` that saves to database a `Flexible` structure `[{ key: akdjkq8238h32, layout: prices, attributes: [attributes] }]`.

What I tried so far mimicking above behaviour makes `FlexibleContent` unable to read the fields' data.

My earlier solution causes other complications and issues (impossible to edit pre-filled Layouts from code), and I'm looking to do something cleaner. 

Thanks for your help

**Comment by Nyratas** [comment]
I'm not sure to understand the issue, but if you want to fill a model's attribute with the default generated JSON, you can use [Nova's `fillInto` method](https://github.com/laravel/nova/blob/0c3ac0da8c47ff775d1282329544f71f1b5631db/src/Fields/Field.php#L328). This method will trigger the field's serialization in the given model's attribute :

```php
$myFlexibleField->fillInto($requestWithFieldValue, $model, $attribute);
```

**Comment by phlisg** [comment]
@Nyratas Thank you for your answer :-)

Unfortunately the link is broken.

I'll have a try, although the whole idea is not to use Nova at all here, as I'd like to create Models and persist them to DB via code.  
It's very easy for non Flexible columns, but things spice up as I want to save data that `FlexibleContent` can parse back into Nova's UI.

What I try to do:
- Get json from API
- create virtual models and fill attributes from json
- persist model in DB

**Comment by Nyratas** [comment]
The link is not broken if you gain acces to Nova's repository, which you should have with a valid license (and that you linked your Nova account with your Github account or something like that).

Does your API return a Flexible's JSON structure or are you supposed to transform your own data into a Flexible structure ?

**Comment by phlisg** [comment]
Hello @Nyratas 

Thank you, the link works :) forgot linking my accounts.

The API doesn't return a Flexible Json structure, I need to transform into it. I used to make my own abstraction of Flexible, but I think I need to use Flexible directly, I just don't see how I can use a `Layout` to compute a database value, if it's possible or if I need to use something else.

Something like: `Raw data` -> `Custom Layout` -> custom layout's value to database
