### ISSUE TITLE
Drag and drop reordering functionality

### ISSUE THREAD

**Issue by f-liva** [whitecube/nova-flexible-content#122]
A functionality of reordering flexible-contents through drag&drop would be useful.

In the case of tens or worse of hundreds of active blocks, reordering one by one with the up/down arrow is like impossible.

**Comment by voidgraphics** [comment]
Agreed.

**Comment by trippo** [comment]
Is there any news on this?

**Comment by Nyratas** [comment]
@trippo not yet. PRs are accepted.

**Comment by Chyzhykal** [comment]
Would be great to put it in the next version, seems for me like really important feature.

**Comment by voidgraphics** [comment]
Added in #374, will be included in version `v1.0.4` shortly
