### ISSUE TITLE
Default value - aka access the data in layouts

### ISSUE THREAD

**Issue by bernhardh** [whitecube/nova-flexible-content#125]
In nova, you would normally set a default value like so:

```
Text::make("Content", "content")
    ->withMeta([
        "value" => $this->content ?? "My default content"
    ])
```

See for example https://github.com/laravel/nova-issues/issues/58#issuecomment-427502568

How can we set a default value for a field inside a layout?

Let's say you have an custom layout class `ContentLayout` which extends of course your `\Whitecube\NovaFlexibleContent\Layouts\Layout`, how can we access the data of the current field?

**Comment by royduin** [comment]
Haven't tested it, but this could work: https://github.com/laravel/nova-issues/issues/58#issuecomment-570067641

**Comment by bernhardh** [comment]
Thanks, that works!
