### ISSUE TITLE
Update returns error 502 on php7.4

### ISSUE THREAD

**Issue by scaventum** [whitecube/nova-flexible-content#130]
Hi, recently i just upgraded to `php7.4` from `php7.3`

The problem is when i tried to update a resource with 2 or more Nova flexible Content fields in it. it does nothing, and error of 502 is shown. It still works normally when creating.

I had to rollback to `php7.3` temporarily until i figured out this issue.

Edit: issue only happens when i have more than 1 flexible fields, something like:

```
return [
...
Flexible::make('Cars')
            ->addLayout('Car', 'car', [
                Text::make('Name')
            ]),
Flexible::make('Drivers')
            ->addLayout('Driver', 'driver', [
                Text::make('Name')
            ]),
...
]
```

**Comment by Nyratas** [comment]
Hi @scaventum,

Could you post more details of the error log ? Thanks.

**Comment by scaventum** [comment]
Hi @Nyratas that's the problem, when i hit update all it returns is 502 error, it shows nothing on my nginx/error.log. When i remove the second Flexible field it works again.

**Comment by buttjer** [comment]
I think it hase something to do with data_get or a strange recursive behavior. I try to dig deeper.

**Comment by nicoaloisio** [comment]
i know it's far from ideal but it seems that I fixed this issue by adding in NovaServiceProvider (in boot method, of course) the following line:
ini_set('error_reporting', E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED);

**Comment by adriaanzon** [comment]
I had the same issue a few months ago (though for some reason I cannot reproduce it anymore; I'll try bisecting to find out what caused it to work again).

When I was debugging this issue, I tried running with `php artisan serve`, and saw that PHP exited with a segmentation fault, causing the 502 error.

It only occurred when all of these were true:
- PHP version is 7.4
- Nova resource has `Whitecube\NovaFlexibleContent\Flexible` field
- Property set by `Whitecube\NovaFlexibleContent\Flexible` has its entry in the `$casts` array set to "json" or "array"
- Nova resource has `Ebess\AdvancedNovaMediaLibrary\Fields\Files` field
- The resolver for the `Flexible` field fills the model property by setting it "directly" (in other words, it calls `setAttribute()` via `__set()` instead of calling `setAttribute()` directly)

When removing one of the conditions above, the segfault went away.

In order to work around this, I created a resolver based on `Whitecube\NovaFlexibleContent\Value\Resolver`, overriding the `set` method to call `setAttribute` directly:

```php
<?php

namespace App\Nova\Flexible\Resolvers;

use Whitecube\NovaFlexibleContent\Value\Resolver;

/**
 * Resolver that works around a segfault that occurs when all of these conditions are true:
 * - PHP version is 7.4
 * - Nova resource has Whitecube\NovaFlexibleContent\Flexible field
 * - Property set by Whitecube\NovaFlexibleContent\Flexible has its entry in the $casts array set to "json" or "array"
 * - Nova resource has Ebess\AdvancedNovaMediaLibrary\Fields\Files field
 * - The resolver for the Flexible field fills the model property by setting it directly
 *   (in other words, it calls setAttribute() via __set() instead of calling setAttribute() directly)
 */
class Php74Resolver extends Resolver
{
    public function set($model, $attribute, $groups)
    {
        // Work around the segfault by using setAttribute instead of setting the property directly
        return $model->setAttribute($attribute, $groups->map(function($group) {
            return [
                'layout' => $group->name(),
                'key' => $group->key(),
                'attributes' => $group->getAttributes()
            ];
        }));
    }
}
```

And used it by setting the `resolver()`:

```php
Flexible::make('External links')
    ->addLayout('YouTube', 'youtube', [
        Youtube::make('URL', 'video_id')->placeholder('YouTube URL')->hideFromIndex(),
    ])
    ->button('Add New Link')
    ->resolver(Php74Resolver::class),
```

**Comment by buttjer** [comment]
And if you are using the accessor with the $this->flexible method in your eloquent model. Make sure you are not using a json cast on the same fields. This is not compatible and can lead to an 502.

**Comment by emilianotisato** [comment]
Thanks @adriaanzon this fix the issue for me also on PHP 7.4 using 2 `Flexible` fields in same resource

**Comment by phlisg** [comment]
Confirming the issue on my end too

I directly modified the default `Resolver` class in the `vendor` folder, it works

**Comment by voidgraphics** [comment]
Thank you @adriaanzon for the workaround!

I have made some pretty substantial changes in the recent versions and would appreciate it a lot if someone familiar with this problem could give it a try with `v0.2.2` to see if it still happens. If it does I will integrate the above solution into the package.

**Comment by michielkempen** [comment]
I can confirm that the bug still exists in `v0.2.2`.

**Comment by phlisg** [comment]
Still running in the issue with latest Nova (3.16.3) and latest Laravel 7 (7.30). For some reason, it only concerns a small bunch of resources using FlexibleContent. Some other resources using less sophisticated FlexibleContents are working. I suspect that nested Flexibles are the issue, despite using @adriaanzon 's answer to make things work.

**Comment by phlisg** [comment]
![image](https://user-images.githubusercontent.com/13777556/102324269-e4fc4080-3f81-11eb-91eb-ad968d26719c.png)

Possible solutions are to modify the output_buffering in php.ini but that didn't work on my end :/

**Comment by phlisg** [comment]
Hello again,

Discovery of the day: 
PHP 7.4.10
Nova 3.16.3
Laravel 7.30
*and* FlexibleContent locked at 0.2.5 -> everything works with @adriaanzon 's solution

I just have my usual issue with some nested flexible content but I can create and edit objects again.
