### ISSUE TITLE
Allow to store data in a nested json field

### ISSUE THREAD

**Issue by bernhardh** [whitecube/nova-flexible-content#131]
Lets say you have a model field called `json_data` which is casted as an `array`.

```php
protected $casts = [
    'json_data' => 'array',
];
```

Into this field, you want to store multiple separete nova-flexible-content fields. For example you have 2 fields like `header` and `body`  where you want to add blocks. The result should look like this:

```json
{
    "header": [{
        "layout": "html",
        "key": "ca36b2efc9f3a2dd",
        "attributes": {
            "title": "Header Block 1"
        }
    }],
    "body": [{
            "layout": "html",
            "key": "asdasdas3fsdfgsdf",
            "attributes": {
                "title": "Body Block 1"
            }
        },
        {
            "layout": "html",
            "key": "bfgdfgsdf3434234",
            "attributes": {
                "title": "Body Block 2"
            }
        }
    ]
}
```

To achive this, I just have to use one of the JSON field packages (for example https://github.com/armincms/json) and wrap the field into it:

```php
use Armincms\Json\Json;

public function fields() {
    return [
        Json::make("json_data", [
            Flexible::make('', 'header')
                ->preset(...),
            Flexible::make('', 'header')
                ->preset(...),
        ])
    ];
}
```

Your package would work out of the box with this setting, only one line in your `HasFlexible` trait makes a problem. I have solved it, by extending it, but you could probably add my change (see pull request), since it is only one line and it adds a feature without messing up existing stuff.

**Comment by Nyratas** [comment]
Hi @bernhardh,

First of all, thanks for the explanation and the (potential) fix. I'll take a look at it as soon as possible.

However, even if I can understand your approach, I think it is a little bit "overkill". In this case, you could simplify nova's UI by implementing 2 separate fields : one for the header, another for the body. This way, the user will not have to suffer from the fields nesting in the UI. Another workaround would have been to create 2 layouts : one for the header and, again, one for the body blocks. This way you would not need to nest them in an unnecessary json structure, you could just identify them on their layout's name.

Just a few thoughts, hope you don't mind! :)

Have a great day.

**Comment by bernhardh** [comment]
Hi @Nyratas,

thanks for the reply and your great package!

I not really understand the problem in making a really minor non breaking change to add additional flexibility to the package, but its totally ok for me since I am now working with an own resolver and saving data to a separate table, since then its easier to work with the advanced-media-library and a couple of other benefits. Thanks for the flexibility with the resolver ;)

Just  to explain, why I still think, that my suggestion is a really usefull fix - look at my real usecase:

I have a model/resource `Page` which represents a webpage. A webpage has different (visible) parts/sections, for example header, jumbotron, above_content, content, sidebar, seo_text, footer, copyright, etc. On the frontend, each section is a field in the json column of the database, but (except for the content) each section has a default fallback content definied in the code. 

This means, in >90% of the pages, the user only enters the content data and the other sections are empty (and use the default logic from the frontend code). Only on special pages, for example on the imprint, special campain pages, etc. the user wants to "overwrite" the default behavior of the different sections. Your suggestion would mean, that I create ~10 extra db columns which are all `NULL` in >90% of the entries, while if I use a single (nested) "section" column, this problem wouldn't occure.

Thanks for reading, I just wanted to keep my initial example as simple as possible.

**Comment by bernhardh** [comment]
Btw. I am confused. You merged my pull request already?

**Comment by ahinkle** [comment]
This is a breaking change. Please see #142.

**Comment by SquareBeard** [comment]
This change breaks doesn't work at all for me.
I'm getting a "Maximum function nesting level reached" error because the `data_get` function calls the model accessors. And of course the model accessor calls $this->flexible again.

I don't even understand how this can work for you ? Am I missing something ?
I'm reverting back to v0.1.13 for now.
