### ISSUE TITLE
Docs missing from repo

### ISSUE THREAD

**Issue by LorenzoSapora** [whitecube/nova-flexible-content#143]
I see the /docs folder, but it has nothing inside for me to edit.

I wanted to document the collapse() function, as it has no documentation on either https://whitecube.github.io/nova-flexible-content/ or the README.

The function has a very singular purpose, but it still needs documenting (as I was going to open an issue asking for the feature before I found it in the class).

**Comment by Nyratas** [comment]
Hi @LorenzoSapora,

The `/docs` folder does contain a `README.md` you could edit. I don't know why the folder was empty for you, but it does contain the source for our https://whitecube.github.io/nova-flexible-content/ page.

**Comment by LorenzoSapora** [comment]
Ah! It _looked_ lesser than the content on the github page. Apologies.
