### ISSUE TITLE
Image with Resolver not working

### ISSUE THREAD

**Issue by Equruler** [whitecube/nova-flexible-content#147]
Do anyone has a example of using Image field and pass it to Resolver?
In Resolver set method, I can't receive any data of the image field in $groups.
And the image did'n't be uploaded to Drive.

Any idea?

**Comment by Nyratas** [comment]
Hi @Equruler,

Sorry for the delay. Is this issue still relevant? Everything seems fine on my side.

I'm closing this issue for now, but do not hesitate to reopen it if necessary. When you do so, could you give a specific example? Thanks.

**Comment by igor-codel1** [comment]
Hi. i got the same issue. when using the Image::make in flexible - it works, but if i use the resolver - image field returns null. Tried around some things, coudln't manage to work image field with the resolver.
Thanx

**Comment by adilbekes** [comment]
Hi, has anyone been able to do this? Image doesn't work with resolver, and how can i define image has many model?

**Comment by peteswan** [comment]
Hi guys, any update on this? Same problem - image null in the attributes array when using resolver in the set method, works fine without resolver.

**Comment by peteswan** [comment]
Hi guys, my mistake - this works when creating, but for some reason, when editing, it doesn't work.
