### ISSUE TITLE
Hidden fields

### ISSUE THREAD

**Issue by njxqlus** [whitecube/nova-flexible-content#149]
![image](https://user-images.githubusercontent.com/15072672/75877240-4b1b3b00-5e28-11ea-969d-ee6599a2eb38.png)

When I making custom Preset I need to hide one of my field with meta default value
```php
$field->addLayout($attribute->name, 'attributes', [
    Text::make(__('nova.type'), 'id')
        ->withMeta(['value' => $attribute->id, 'type'=> 'hidden'])
        ->readonly(),
    Text::make(__('nova.value'), 'value')
])->fullWidth();
```

But this only hide input not label. How I can hide all row?

--- 
Or maybe I can pass this value to resolver with another method? `->withMeta()` on `addLayout` don't make anything

**Comment by voidgraphics** [comment]
See https://github.com/laravel/nova-issues/issues/666

**Comment by njxqlus** [comment]
> See [laravel/nova-issues#666](https://github.com/laravel/nova-issues/issues/666)

I set `type=>hidden`, `->hideWhenCreating()->hideWhenUpdating()`, this not work.

Or what do you mean?

**Comment by voidgraphics** [comment]
I mean this is not a nova-flexible-content related problem. You can not natively hide the label this way. There is a third-party package that adds a hidden field in the comments of that issue.

**Comment by njxqlus** [comment]
@voidgraphics btw this package not working properly too.

![image](https://user-images.githubusercontent.com/15072672/75879321-43f62c00-5e2c-11ea-9247-4fba7fdd8007.png)

My code: 
```php
HiddenField::make(__('nova.type'), 'id')->withMeta(['value' => $attribute->id])->hideFromDetail(),
```

**Comment by MJTheOne** [comment]
This should not be closed because it is not saving the default value of a Hidden field
