### ISSUE TITLE
Mutator not working

### ISSUE THREAD

**Issue by packytagliaferro** [whitecube/nova-flexible-content#152]
I am trying to use a mutator as you described in the docs but nothing gets returned. If I just use `flexible` method in a blade view it does work? I have the trait on the model and again it does work if I dont add a mutator and just call the method in a blade file.

**Not working in model**:

```
public function getHoursAttribute()
    {
        return $this->flexible('hours');
    }
```

then in my blade I used: `$location->hours`

**Does work in blade:**
No mutator 

then in my blade I used: ` $location->flexible('hours')`

**Comment by voidgraphics** [comment]
This is because when you call `flexible('hours')`, it will go through your mutator again, in an infinite loop. You must name your mutator differently than the original attribute.

**Comment by packytagliaferro** [comment]
This makes sense. Your example just had me confused at first:

```
 public function getFlexibleContentAttribute()
    {
        return $this->flexible('flexible-content');
    }
```

Since your mutator and column are the same name here. 

Thanks

**Comment by voidgraphics** [comment]
We'll update it to be more clear. That being said `getFlexibleContentAttribute` translates to `flexibleContent` and not `flexible-content`.
