### ISSUE TITLE
NovaTinyMCE package not supported

### ISSUE THREAD

**Issue by MajkieS** [whitecube/nova-flexible-content#156]
Hi there,

this package is not supported and not rendered. https://github.com/emilianotisato/nova-tinymce
Can you please add support for it?

Thanks

**Comment by NioTeX** [comment]
I actually tested this, and the 2 packages work together. The only real issues is that if you move the components up/down it's content disappears and is not editable anymore.

**Comment by NioTeX** [comment]
@voidgraphics Have you by any chance seen similar issues? Maybe I could create a PR here or over at nova-tinymce if I would understand why the issue happens exactly.

**Comment by voidgraphics** [comment]
@NioTeX Sorry, I do not use that package, so I haven't encountered any of these problems. I don't know where the problem could come from at the top of my head.

**Comment by NioTeX** [comment]
@voidgraphics thanks for the reply. Just to confirm, I am asking about any such issue where the content of a field disappears on reorder, possibly do the init scripts not running after DOM element remove/add. Thanks in advance!

**Comment by youngestdj** [comment]
@NioTeX is there a solution to this? Or any other similar packages to NovaTinyMCE that works well with nova-flexible-content. I am currently facing this issue.

**Comment by NioTeX** [comment]
@youngestdj Did not find a solution sadly.

**Comment by manogi** [comment]
@youngestdj I did not experience these problems with [nova-tiptap](https://github.com/manogi/nova-tiptap). DISCLAIMER: I am the maintainer of that package ;-). Also: my package does NOT include file uploads / image uploads through the editor.

**Comment by youngestdj** [comment]
Hi @manogi does your package support the inclusion of special characters? I use a plugin with NovaTinyMCE that helps me include special characters in the editor

**Comment by manogi** [comment]
@youngestdj I'm not sure I quite understand what you mean by "inclusion of special characters". It has no special plugin for special characters, but you can type any UTF-8 character you like. Maybe it is best if you just try it out, that is probably quicker than trying to discuss this here - also this is not the right place as this is a "Nova Flexible Content" issue ;-)

**Comment by JonathanDoelan** [comment]
I’ve written a dirty, temporary solution:

```
->help(
	'<button type="button" onclick="if (window.tinyMCE && tinyMCE.editors.length) {
		var _data = [];

		for (var i = 0; i < tinyMCE.editors.length; i++) {
			if (tinyMCE.editors[i].getContent()){
				_data.push({
					el: tinyMCE.editors[i],
					settings: tinyMCE.editors[i].settings,
				});
			}
		}

		for (var i = 0; i < _data.length; i++) {
			_data[i].el.remove();

			tinyMCE.init(
				_data[i].settings
			);
		}
	}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="11" height="11" class="fill-current align-middle"><path d="M6 18.7V21a1 1 0 0 1-2 0v-5a1 1 0 0 1 1-1h5a1 1 0 1 1 0 2H7.1A7 7 0 0 0 19 12a1 1 0 1 1 2 0 9 9 0 0 1-15 6.7zM18 5.3V3a1 1 0 0 1 2 0v5a1 1 0 0 1-1 1h-5a1 1 0 0 1 0-2h2.9A7 7 0 0 0 5 12a1 1 0 1 1-2 0 9 9 0 0 1 15-6.7z"></path></svg> refresh</button>'
)
```

Add this to the tinyMCE-field’s help method and a "refresh" button will appear. Clicking on that button will reinitialize every tinymce-instance (that is not empty, because empty ones lead to an error)

Would love to see a better solution!

**Comment by BoiteBeet** [comment]
Using the previous response from @JonathanDoelan I fixed it by adding a watcher in FormGroup on the 'index' props:
```php
    watch: {
        index() {
            if(!window.tinyMCE) {
                return;
            }
            this.$nextTick(() => {
                tinyMCE.editors
                    .filter((editor) => editor.id.startsWith(this.group.key)) //Getting only the editors for the current group
                    .forEach((editor) => {
                        let settings = editor.settings;
                        editor.remove();
                        tinyMCE.init(settings);
                    })
            });
        }
    },
```

**Comment by aspirecya** [comment]
Hello, any news on natively supporting TinyMCE without these fixes?
Thank you!

**Comment by toonvandenbos** [comment]
Hi, as explained by @voidgraphics we do not use TinyMCE on our projects and we're therefore not sure our solution would suit that package's integration.

However, from what I can see in the suggested solutions, this seems to be a "problem" with TinyMCE itself and the way it is rendered in the DOM. If someone knows which event needs to be emitted in order to trigger their editor's update when moving up/down, you can open a PR and we'll merge it.

Thinking a bit further, I think there should be a proper "Nova" way (API/event) to inform fields they need to re-render or update their implementation. Otherwise we're doomed to implement every popular field's logic within this package, which is not something I want to get started with.
