### ISSUE TITLE
Local Scope on ->flexible()?

### ISSUE THREAD

**Issue by latwelve** [whitecube/nova-flexible-content#163]
Sorry for my lack of knowledge but is it possible to setup a local scope on a model so that I can do something like this:

```
  public function scopePrices($query)
    {
            return $query->flexible('childcare_prices')
            ->map(
            function($prices) {
                return $prices['attributes'];
            })
            ->where('currency', 'gbp');

    }
```

**Comment by Nyratas** [comment]
Hi @latwelve,

No, it is not possible to call `flexible` on a query. But you could achieve your request by attaching [the Query Builder's "JSON Where Clauses"](https://laravel.com/docs/7.x/queries#json-where-clauses) on the flexible column. If needed, just take a look at the field's JSON structure in your database.

**Comment by latwelve** [comment]
Sorry I'm back.. I've just run a test on a scope with your advice but the square brackets the json is wrapped in is throwing it off.

```
    public function scopePrices($query, $currency)
    {
        return $query->whereJsonContains('childcare_prices->attributes->currency', $currency);
    }
```

Example of storred json:
`[{"key": "599445f9e289b72b", "layout": "childcare_prices", "attributes": {"att_a": "1000", "att_b": "200", "currency": "gbp", "att_c": "400", "att_d": "300", "att_e": "600", "att_f": "500"}}, {"key": "bd104782c2be9194", "layout": "childcare_prices", "attributes": {"att_a": "1", "att_b": "202", "currency": "eur", "att_c": "404", "att_d": "303", "att_e": "606", "att_f": "505"}}]`


My query minus the square brackets works well, so I just don't know why they are there or how to handle them sorry?

**Comment by Nyratas** [comment]
The square brackets mean it's an array. 

Maybe take a look at [this solution](https://stackoverflow.com/questions/53641403/search-in-json-column-with-laravel).

**Comment by latwelve** [comment]
> The square brackets mean it's an array.
> 
> Maybe take a look at [this solution](https://stackoverflow.com/questions/53641403/search-in-json-column-with-laravel).

Thank you for putting me on the right track, that works well

`DB::table('availabilities')->whereJsonContains('prices',[['attributes' => ['currency' => 'gbp']]])->get()`

Sorry to keep asking basic questions but did I miss something obvious in the docs? I thought by default it saves as JSON not wrapped in square brackets or if only 1 layout type was defined (or only ever going to be used)

**Comment by Nyratas** [comment]
The square brackets are part of the JSON syntax. As the field is meant to be repeated, each layout (even when there's only one) is an item in the field's layouts array, which is the only logical structure for this kind of behavior.
