### ISSUE TITLE
How add many relationship ?

### ISSUE THREAD

**Issue by piterssson** [whitecube/nova-flexible-content#164]
How add many relationship ?

I'm using resolver to save data another table. But I would like to save every preset to another tables.

**Comment by Nyratas** [comment]
Hi,

A similar example is explained in the [full docs](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes).

**Comment by piterssson** [comment]
> Hi,
> 
> A similar example is explained in the [full docs](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes).

I have three table with data. Creating is working but after saved  and sort I nothing see.

![Zrzut ekranu z 2020-04-10 12-42-52](https://user-images.githubusercontent.com/16086241/78985382-e63eb900-7b28-11ea-9c28-b67c1b40da03.png)
![Zrzut ekranu z 2020-04-10 12-42-13](https://user-images.githubusercontent.com/16086241/78985384-e6d74f80-7b28-11ea-9c3e-04d70817bade.png)

**Comment by Nyratas** [comment]
1. What do you mean with different tables ? 
2. Did you check if your custom works correctly for both the getter & setter methods ?

**Comment by piterssson** [comment]
> 1. What do you mean with different tables ?
> 2. Did you check if your custom works correctly for both the getter & setter methods ?

1. Text save to Text Table and Twitter save to Twitter table (in one resolver)
2. I'm checking custom getter & setter methods

**Comment by piterssson** [comment]
![Zrzut ekranu z 2020-04-10 13-54-53](https://user-images.githubusercontent.com/16086241/78990587-1725ea80-7b37-11ea-9c05-5fe1d13e5e91.png)
