### ISSUE TITLE
Currency field

### ISSUE THREAD

**Issue by zalazdi** [whitecube/nova-flexible-content#166]
I found a bug, when we try to use `Currency` field (or other with `displayUsing` function applied):

```php
Flexible::make('Invoices', 'invoices')
    ->addLayout('Invoice', 'invoice', [
        Text::make('No', 'number'),
        Currency::make('Amount', 'amount')
    ]),
```

For second row it's trying to run `displayUsing` two times on value, for third three times and so on...

For now, I've creadet custom Layout class and overwrited:
```php
public function duplicateAndHydrate($key, array $attributes = [])
{
    $fields = collect($this->fields());

    return new static(
        $this->title,
        $this->name,
        $fields,
        $key,
        $attributes
    );
}
```
So it's making a new fields instances for every repeated row, so `displayUsing` is run only once.

I think it could be good idea to change layout definition from array to clousure - and execute method everytime we need it.

**Comment by voidgraphics** [comment]
Thanks for the report and for including a temporary fix! Very helpful. We'll look into this soon.
