### ISSUE TITLE
Compatibility with Spatie\MediaLibrary v8

### ISSUE THREAD

**Issue by DarrenTheDev** [whitecube/nova-flexible-content#173]
Version 8 of `spatie/laravel-medialibrary` has made quite a few name changes. https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md

This includes renaming the `HasMediaTrait` used by the `HasMediaLibrary` concern.

The version of `ebess/advanced-nova-media-library` that supports Nova 3 only supports v8 of `spatie/laravel-medialibrary`. So at the moment it seems impossible to use Nova 3, Advanced Nova Media Library and Nova Flexible Content together. https://github.com/ebess/advanced-nova-media-library/blob/3.0.0/composer.json

A bit of a dependency hell!

**Comment by voidgraphics** [comment]
Thank you for reporting, we will get it up to date soon :)

**Comment by voidgraphics** [comment]
Included in [v0.2.1](https://github.com/whitecube/nova-flexible-content/tree/v0.2.1)

**Comment by eboye** [comment]
After latest update, this seems to be the problem again

![image](https://github.com/whitecube/nova-flexible-content/assets/624357/4f47b02b-eb47-4fd4-9b78-5ccd14c22615)

whitecube/nova-flexible-content v1.0.14
ebess/advanced-nova-media-library 4.1.7
