### ISSUE TITLE
How do you define accessors for layouts? So I can fetch a row value in my view?

### ISSUE THREAD

**Issue by notflip** [whitecube/nova-flexible-content#178]
First of all, this plugin is amazing! Thank you for the great work.

In the docs I see
_"Layouts are some kind of fake models. They use Laravel's HasAttributes trait, which means you can define accessors & mutators for the layout's attributes."_

Where can I define those accessors?

**Comment by voidgraphics** [comment]
Hi, thanks! Glad you like it!

You need a [custom layout class](https://whitecube.github.io/nova-flexible-content/#/?id=custom-layout-classes): 

```php
namespace App\Nova\Flexible\Layouts;

use Laravel\Nova\Fields\Text;
use Whitecube\NovaFlexibleContent\Layouts\Layout;

class SimpleWysiwygLayout extends Layout
{
    protected $name = 'wysiwyg';
    protected $title = 'Simple content section';

    public function fields()
    {
        return [
            Text::make('Title'),
        ];
    }
   
    // Define your accessors here
    public function getAllcapsTitleAttribute()
    {
        return strtoupper($this->title);
    }
}
```

**Comment by notflip** [comment]
Thanks for the fast response, I didn't see it in the docs, but how do you retrieve field values without using accessors? What's the default way of doing this?

**Comment by voidgraphics** [comment]
You should use casts for flexible fields [as explained here](https://github.com/whitecube/nova-flexible-content#using-flexible-values-in-views).
