### ISSUE TITLE
Is it possible to change the collapsable header?

### ISSUE THREAD

**Issue by notflip** [whitecube/nova-flexible-content#179]
Is it possible to change the string next to the collapse button, to for example a value from one of the fields? Thank you.

![Screenshot 2020-05-07 at 15 14 14](https://user-images.githubusercontent.com/4146384/81298745-7cf18d80-9075-11ea-8b5e-9338cb34bcc1.png)

**Comment by Nyratas** [comment]
Hi @notflip,

No, that's not possible yet. If this is a feature you'd really want to implement, feel free to open a PR. Thanks!

**Comment by voidgraphics** [comment]
This was suggested in #136, it would be a very nice feature to have.
