### ISSUE TITLE
[question] Static layouts 

### ISSUE THREAD

**Issue by jornwildenbeest** [whitecube/nova-flexible-content#181]
Is it possible add static layouts?

For example, i have 3 kinds of layouts in my nova model.
One for text, one for images and one for video's.
I don't want the user to add unlimited layouts, and every layout needs to be used.
So the limit option is not an option because the user can still add 2 of the same layouts.

So I thought maybe I can make the 3 kind of layouts static, so the users only has the option to fill the fields in layouts without adding the layouts, because the layouts are already added. 

But I can't find it anywhere in the docs if this is possible..

**Comment by voidgraphics** [comment]
Sounds to me like you need to use nova panels instead of a flexible field.
