### ISSUE TITLE
Default for Flexible as Action field

### ISSUE THREAD

**Issue by daanadriaan** [whitecube/nova-flexible-content#184]
Hi guys,

I've been using Flexible in my actions modal, handling the content manually in the handle function of the action. It works great! However, I'm having difficulty understanding how to set a default first layout. So, a layout that is already open.

The flexible field has no input or attribute since it does not make use of any resource. I have tried a withMeta(['value' => *json that is usually returned from the flexible field*]) but no luck.

Any ideas?

**Comment by looksystems** [comment]
I tried something similar... I got my layout to appear but without any fields.

May be the fact that there's default value has been provided needs to be detected and something like buildGroups() called? Hey, just a guess!

`
            ->withMeta([
                'value' => [
                    [
                        "layout" => "item",
                        "key" => uniqid(),
                        "attributes" => [
                            "quantity" => "1",
                            "lengthWithUnits" => " '',
                            "diameterWithUnits" => "''
                        ]
                    ],
                ]
            ])
`

**Comment by daanadriaan** [comment]
@looksystems Sounds promising. I still don't even get my layout to appear.

**Comment by daanadriaan** [comment]
@looksystems got it. The attributes need to be Nova fields.

->withMeta([ 'value' => [ [
                "layout" => "item",
                "key" => uniqid(),
                "attributes" => [
                    Text::make('Title)
                        ->withMeta(['value' => 'Default Title']]),

Would be nice to see an easier way to apply defaults, without the duplicate fieldcode.

**Comment by looksystems** [comment]
Great work! Thank you.

I de-duped like this...

        $itemFields = [
            Number::make('Quantity')->rules('required')->min(1)->withMeta([
                'value' => 1
            ]),
            Text::make('Length', 'lengthWithUnits')->rules('required')->withMeta([
                'extraAttributes' => [
                    'placeholder' => 'with units',
                ],
                'value' => 'default length'
            ]),
            Text::make('Diameter', 'diameterWithUnits')->rules('required')->withMeta([
                'extraAttributes' => [
                    'placeholder' => 'with units',
                ],
                'value' => 'default diameter'
            ]),
        ];

        return [
            Flexible::make('layout')->addLayout(
                'Item', 'item', $itemFields
            )
            ->withMeta([
                'value' => [
                    (object)[
                        "layout" => "item",
                        "key" => uniqid(),
                        "attributes" => $itemFields
                    ]
                ]
            ])
            ->button('Add')
        ];

**Comment by daanadriaan** [comment]
Nice! Got me inspired to build this crazy workaround carnaval haha

`public function fields() {
        $flexible = Flexible::make('Velden', 'fields')
            ->button('Voeg nieuw type toe');

        $defaults = [];

        foreach(\App\Models\Config\DocumentType::all() as $type){
     
            $fields = [
                Text::make('Type', 'field_type')
                    ->withMeta(['value' => $type->field_type]]),
                Text::make('Titel', 'title')
                    ->withMeta(['value' => $type->name ?? '']),
                Textarea::make('Begeleidende tekst', 'description')
                    ->withMeta(['value' => $type->description ?? ''])
            ];

            $flexible = $flexible->addLayout($type->name, $type->slug, $fields);

            if($type->default){
                $defaults[] = ["layout" => $type->slug, "key" => uniqid(), "attributes" => $fields];
            }
        }

        return [
            $flexible->collapsed()->withMeta([ 'value' => $defaults])
        ];
    }`

**Comment by Nyratas** [comment]
Hi,

Sorry I'm late to the party.

Default flexible values sound like a nice feature to have. Feel free to suggest a PR implementing it, but if you do so please keep in mind that we want to keep the package as flexible as possible, meaning the feature should not only cover your specific use case scenarios. Thanks!

Indeed, `buildGroups` should be called at some point in order to populate the layouts in a secure way.

**Comment by JurjenRoels** [comment]
I would love this functionality.
