### ISSUE TITLE
"Undefined property: Laravel\\Nova\\Fields\\Text::$requiredCallback"

### ISSUE THREAD

**Issue by iDoes123** [whitecube/nova-flexible-content#196]
When using the most recent version (0.2.4) I keep getting this error on whatever field I put in the addLayout.

"Undefined property: Laravel\\Nova\\Fields\\Text::$requiredCallback"

For example, when using Text field:

Flexible::make(__('content'), 'content')
				->addLayout(__('Information'), 'text', [
					Text::make(__('text'))
				]),

This works fine in older versions.

The error is triggered in
.../vendor/whitecube/nova-flexible-content/src/Layouts/Layout.php",
    "line": 247,

I also used your example code found on https://whitecube.github.io/nova-flexible-content/#/?id=usage. But I kept on getting the same error.

Hope you can fix it or explain to me what I am doing wrong. In the meantime I am using version 0.1.12, cause I am certain everything I need works in that one.

**Comment by Nyratas** [comment]
Hi @iDoes123,

Could you try using the `dev-master` branch and tell me if it solves your problem? Thanks!

**Comment by iDoes123** [comment]
Hey @Nyratas ,

This seems to fix it! Thank you :)
