### ISSUE TITLE
Limiting Custom Layout

### ISSUE THREAD

**Issue by Petoches** [whitecube/nova-flexible-content#199]
Hello,

Is there a way to limit a custom layout to a specific number and not the all flexible field ?

Thanks

**Comment by voidgraphics** [comment]
Hi, this is planned (duplicate of #3) but has not been added yet to the package. It's definitely a feature we want to add but have not found the time to do so yet.

We would love to accept a PR if anyone wants to give it a try.

**Comment by Petoches** [comment]
https://github.com/whitecube/nova-flexible-content/pull/200
