### ISSUE TITLE
Ability to use for hasMany Relations

### ISSUE THREAD

**Issue by petericebear** [whitecube/nova-flexible-content#207]
Hi,

Could it be possible to make use of the layouts for hasMany relations on the layout?
So that a set of fields could be added into sub records.

For instance Organisation => hasMany Locations

Organisation
id,
name

Location
id
organisation_id
name
address
city
image

So that the adding and editing make use of the design to fill the relations?

**Comment by Nyratas** [comment]
Hi @petericebear !

It is possible to achieve this using a [Custom Resolver](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes). 

As I mentionned on [Twitter](https://twitter.com/petericebear/status/1284156990483304455?s=19), we could work on an easier way to implement this behavior using a similar approach as the built-in HasMany field.

**Comment by scramatte** [comment]
Hello,

Can you post an example here of how can implement hasMany relationship?
Thank you
