### ISSUE TITLE
Can't get Resolver to work

### ISSUE THREAD

**Issue by codealliance** [whitecube/nova-flexible-content#213]
Hello 
i am trying to use a BelongsTo relationship in a layout
The resource using layout is in the namespace Codealliance\Offers\Nova;
And the resource used is is Codealliance\ProjectsServices\Nova\Service

now i wonder how the resolver should be placed with what namespaces to get it work
i have ServiceResolver and tried in the App\Nova namespace and in the namespace Codealliance\Offers\Nova\Flexible\Resolvers and in the namespace Codealliance\ProjectsServices\Nova\Flexible\Resolvers;
greets

**Comment by Nyratas** [comment]
Hi @codealliance,

I'm not sure what you're trying to achieve, but:

1. Relationships between a layout and a model only work if the layout can be represented by a model itself (meaning the layout's attributes are stored in a dedicated table). The field's default behavior is to be stored as JSON in an attribute, which is therefore not usable in relationships.
2. The resolver's namespace doesn't matter when it is properly referenced in your classes (`use Namespace\To\My\Resolver;`)

Take a look at the docs for more information on [Custom Resolver Classes](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes). The explained example uses a relationship, which should be very similar to what you are doing.

**Comment by codealliance** [comment]
HI
yes i checked the example before and wrote issue because didnt see anything on the layout form.
I am just trying to have a layout with a form containing a Resource in a BelongsTo relationshop.

i cant get the dropdown showing up.
greets

**Comment by Athuli7** [comment]
This is an issue. There is no documentation oh how to enable the resolver in the field config.
