### ISSUE TITLE
Stop a resource form from being submitted on enter/ return press.

### ISSUE THREAD

**Issue by atmediauk** [whitecube/nova-flexible-content#221]
If a user presses the enter/ return key on a flexible content field the whole resource is unintentionally submitted.

To avoid confusion the form submission should be left to the designated action buttons at the bottom of the resource and not interfered with.

Would it be possible to stop this? E.g prevent it or maybe instead insert a new field etc.

**Comment by Nyratas** [comment]
Hi @atmediauk,

Thanks for your feedback ! It seems to me all fields have this behavior, even the most basic ones. We did not add our own submitting events on the enter or return keys, it is the browser's default behavior. I'd suggest creating an issue on the Nova-issues repository instead.
