### ISSUE TITLE
Call to undefined method App\Model::getLayoutFields()

### ISSUE THREAD

**Issue by syamimhazmi** [whitecube/nova-flexible-content#226]
As the title above. I've created LocationPreset for booking where the booking has many locations. I want to load in view and update page, but it gives me this error. Am I doing it wrong?

`<?php

namespace App\Nova\Flexible\Presets\Booking;

use App\Booking;
use App\BookingLocation;
use Whitecube\NovaFlexibleContent\Flexible;
use Whitecube\NovaFlexibleContent\Layouts\Preset;

class LocationPreset extends Preset
{
    /**
     * The available booking
     *
     * @var Illuminate\Support\Collection
     */
    protected $booking;

    /**
     * The available locations
     *
     * @var Illuminate\Support\Collection
     */
    protected $locations;

    /**
     * Create a new preset instance
     *
     * @return void
     */
    public function __construct()
    {
        $this->booking = Booking::orderBy('id')->first();
        $this->locations = $this->booking->locations()->orderBy('id')->get();
    }

    /**
     * Execute the preset configuration
     *
     * @return void
     */
    public function handle(Flexible $field)
    {
        $field->button('Add new locations');
        $field->confirmRemove($label = '', $yes = 'Delete', $no = 'Cancel');
        $field->resolver(\App\Nova\Flexible\Resolvers\Booking\LocationResolver::class);
        // $field->help('Go to the "<strong>Page blocks</strong>" Resource in order to add new WYSIWYG block types.');

        $this->locations->each(function($location) use ($field) {
            $field->addLayout($location->description, $location->id, $location->getLayoutFields());
            // $field->addLayout($location->description, $location->id);
        });
    }
}
`

**Comment by voidgraphics** [comment]
`getLayoutFields()` is just example code. You have to pass in an array of fields, whichever way you prefer. Refer to [this](https://whitecube.github.io/nova-flexible-content/#/?id=adding-layouts) if you're not sure how the `addLayout` method works.
