### ISSUE TITLE
Making Advanced Nova Media Library work with digitalcloud/multilingual-nova

### ISSUE THREAD

**Issue by JurjenRoels** [whitecube/nova-flexible-content#230]
It would be nice if you could add different images to a translation.

This way you could have an image with includes language specifics, to a translated item.

**Comment by Nyratas** [comment]
Is this related to Flexible Content ? Does it work outside a flexible field ?

**Comment by JurjenRoels** [comment]
I will verify that tomorrow.



Verstuurd vanaf mijn iPhone

**Comment by JurjenRoels** [comment]
Hi Toon,

Basically it does not work out of the box.

Combining the things would be great!

I found this: https://github.com/spatie/laravel-medialibrary/issues/1144

So, it is a feature request?

**Comment by Nyratas** [comment]
Wel... I still don't see how this is related to flexible-content if the package combination you're talking about does not work outside a flexible field (at least, that's what I understand by "it does not work out of the box"). Could you tell me why exactly this has something to do with the "nova-flexible-content" package ? And if it does not, I'd suggest taking opening an issue or a PR on the package's repository that actually provoques the problem.
