### ISSUE TITLE
Is it possible to create nested Flexible fields?

### ISSUE THREAD

**Issue by 949mac** [whitecube/nova-flexible-content#24]
For example: 

The following source code appears to work on building the layout, but when the subfield (Flexible field) is added, then all subsequent subfields share the data from the first subfield defined.

```
Flexible::make('Fields')
	->addLayout('Simple content section', 'wysiwyg', [
		Text::make('Title'),
	])
	->addLayout('Video section', 'video', [
		Text::make('Title'),
		
		// Sub Flexible Layout
		Flexible::make('Fields')
			->addLayout('Simple content section', 'wysiwyg', [
				Text::make('Title'),
			])
			->addLayout('Video section', 'video', [
				Text::make('Title'),
			])
	])
```

For example:

![image](https://user-images.githubusercontent.com/23151962/57589219-d7ddbc80-74d5-11e9-82af-81a71b2b42a9.png)

Thank you!

**Comment by Nyratas** [comment]
Hi @949mac,

Nested Flexible _should_ work, I use them quite often. I'll test your setup and try to figure out what's happening, but I have to say this issue is quite unexpected since each layout group has its own identifier.

Thanks for reporting this.

**Comment by 949mac** [comment]
@Nyratas, thanks for looking. I'm on Nova v2.0.3.

Best Regards,

Mike

**Comment by jackabox** [comment]
This worked as expected for me in v0.1.5, however, the update to v0.1.6 seems to be the thing that's busted this and stopped keys being unique. @949mac if you try using version 0.1.5 and see if that works?

**Comment by alloyking** [comment]
Nested content has 'mostly' worked fine for me.  I'm currently on v0.1.6 and V2.0.3 of Nova.  The issue that I do have is that nested data is lost when entries are reordered.

**Comment by Nyratas** [comment]
Latest tests with `Nova v2.0.9` and `dev-master` (upcoming v0.1.8) are positive. Closed this issue since none of the cases seems to cause trouble anymore since 603e4a9.
