### ISSUE TITLE
->help('text') not working

### ISSUE THREAD

**Issue by JonathanDoelan** [whitecube/nova-flexible-content#243]
Help text is not working:

```
Flexible::make('Flexible')
	->help('not working')
```

Maybe this helps: [https://github.com/laravel/nova-issues/issues/3095#issuecomment-737142016](https://github.com/laravel/nova-issues/issues/3095#issuecomment-737142016)

**Comment by Jared0430** [comment]
Would be nice to see this fixed!

**Comment by JonathanDoelan** [comment]
@voidgraphics This still does not work!!!

**Comment by Nyratas** [comment]
@JonathanDoelan it has not been released yet. Did you try it using `dev-master` ?
