### ISSUE TITLE
Possibility to exchange data/listen events between layouts

### ISSUE THREAD

**Issue by eAvio** [whitecube/nova-flexible-content#249]
We for example have date field that exist in all layouts. 

Whenever date is changed it should be updated on all layouts.

We also have some other dependent fields - for example if in resource (outside flexible-content) select specific user group then in the flexible-content we would like to show only users from that group.

Any suggestion how this would be achievable or where to search for future info?

Thank you,
G

**Comment by Nyratas** [comment]
Hi @eAvio,

I'm not even sure Nova has a feature that would let you do that on "normal" fields. This sounds to me as a front-end (JS) event that would fire an AJAX update request for some specific fields. I'm not sure, but [maybe this helps](https://stackoverflow.com/questions/58350443/update-sibling-input-fields-from-custom-field).
