### ISSUE TITLE
How can i get layout key in layout class?

### ISSUE THREAD

**Issue by kayacekovic** [whitecube/nova-flexible-content#252]

**Comment by Nyratas** [comment]
`->key()`

**Comment by kayacekovic** [comment]
> `->key()`

![Screenshot_20210118_120852](https://user-images.githubusercontent.com/32109756/104894652-08058000-5986-11eb-9dc2-098b68e5a6dd.png)
i using like this in layout class. but return empty.

**Comment by kayacekovic** [comment]
> > `->key()`
> 
> ![Screenshot_20210118_120852](https://user-images.githubusercontent.com/32109756/104894652-08058000-5986-11eb-9dc2-098b68e5a6dd.png)
> i using like this in layout class. but return empty.

i could get key in `__construct`. currently solved my problem.
