### ISSUE TITLE
Get the value of a field inside Flexible content before submit the form

### ISSUE THREAD

**Issue by Pamposgsk** [whitecube/nova-flexible-content#253]
Hi,
Is there a possibility to get the value of a field inside flexible-content and use it in order to use it in  a related field?
Thanks in advanced

**Comment by Nyratas** [comment]
Hi,
Yes, you should be able to do that using a dependency-field package or something similar. It is important to know that each group is considered as a new "Form" root, which can make it difficult to access it from the outside.

**Comment by Pamposgsk** [comment]
> Hi,
> Yes, you should be able to do that using a dependency-field package or something similar. It is important to know that each group is considered as a new "Form" root, which can make it difficult to access it from the outside.

I tried all existing packages e.g child select ,nova ajax select etc but none is responding inside flexible content.If I use those packages outside flexible they perfectly works.
Do you know how to make it work?

**Comment by Nyratas** [comment]
No I have no idea right now since I do not use those packages. If you notice something that could be changed in this package in order to enhance its compatibility with another one, feel free to suggest a PR.

**Comment by Pamposgsk** [comment]
Ok thanks!kindly if you know suggest me a dependency-field package that is compatible with flexible content.
Thanks
