### ISSUE TITLE
JS error: TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by giancanuz** [whitecube/nova-flexible-content#27]
I am trying to use this one but I get js error when trying to save. If I don't add any layout object is currectly saved.
`
		$recapiti_field = Flexible::make("recapiti", "recapiti");
		$recapiti_field = $recapiti_field->addLayout('Recapito', 'recapito_layout', [
			Text::make('Recapito','recapito'),
		]);
		$fields[] = $recapiti_field;
`

recapiti is model attribute name (db column) declared as mediumtext and casted as "json" in my model. I've tried to cast it to "array" and don't cast it at all, but outcome is the same. 
Any ideas?

This is the complete js error:

`
vendor.js?id=da751a53228a35fab7c4:1 TypeError: Cannot read property 'status' of undefined
    at p.<anonymous> (app.js?id=e278aec4bd99815664dd:1)
    at y (app.js?id=e278aec4bd99815664dd:1)
    at Generator._invoke (app.js?id=e278aec4bd99815664dd:1)
    at Generator.e.<computed> [as next] (app.js?id=e278aec4bd99815664dd:1)
    at o (app.js?id=e278aec4bd99815664dd:1)
    at app.js?id=e278aec4bd99815664dd:1
    at new Promise (<anonymous>)
    at new t (app.js?id=e278aec4bd99815664dd:1)
    at p.<anonymous> (app.js?id=e278aec4bd99815664dd:1)
    at p.<anonymous> (app.js?id=e278aec4bd99815664dd:1)
`

**Comment by Nyratas** [comment]
Hi @giancanuz,

First of all (but that shouldn't be the reason of your error), you're defining your field in a weird way.

Instead of 

```php
$recapiti_field = Flexible::make("recapiti", "recapiti");
$recapiti_field = $recapiti_field->addLayout('Recapito', 'recapito_layout', [ Text::make('Recapito','recapito'), ]);
$fields[] = $recapiti_field;
```

Try something more readable like

```php
$recapiti_field = Flexible::make('Recapiti');
$recapiti_field->addLayout('Recapito', 'recapito_layout', [Text::make('Recapito')]);

$fields[] = $recapiti_field;
```

Or 

```php
$fields[] = Flexible::make("recapiti", "recapiti")
      ->addLayout('Recapito', 'recapito_layout', [Text::make('Recapito')]);
```

It's not required to cast the model's flexible attribute to anything, the package will handle it on its own, but this shouldn't be linked to your problem  either.

Could you tell me which version of the package and Nova you're using? Thank you!

**Comment by giancanuz** [comment]
thank you for replying so fast.
at the moment  I'm using:
- laravel/nova 2.0.5 
- whitecube/nova-flexible-content v0.1.6
let me know if you need a complete list of installed packages

**Comment by voidgraphics** [comment]
Hi @giancanuz, I am trying to replicate your issue but everything works fine for me. I have installed the same package versions you are describing and I copy/pasted your code.

Can you provide more information or maybe try to set up a repo that reproduces your problem?

Thanks

**Comment by giancanuz** [comment]
@voidgraphics here it is my composer.lock 
 I think it's due to some external packages conflict, so it should be enough.
Let me know if you need a complete environment and I'll try to clean up my actual project to provide you one.

[composer.lock.zip](https://github.com/whitecube/nova-flexible-content/files/3240923/composer.lock.zip)

**Comment by voidgraphics** [comment]
Thanks, however having only the composer.lock doesn't let me reproduce the complexity of your nova setup. I would need to know which packages are actually registered in your app.

If you wouldn't mind sharing your project or trying to make the most barebones one that actually reproduces the bug, that'd be great!

**Comment by flxsource** [comment]
It looks to me like `values` in `group.js` is not returning a proper `FormData` object. Instead, the `FormData` is under a property called `fd`. The below change on line 37 of `group.js` seems to fix this and successfully save, but then causes a number of "property of method not defined" errors when viewing the saved item.

`
for(var item of this.values().fd) {
`

Hope this helps

**Comment by flxsource** [comment]
This issue appears to be caused by another package: [xhook](https://github.com/jpillora/xhook), which is used by [tanmuhittin/nova-scroll-top](https://github.com/tanmuhittin/nova-scroll-top). The work around detailed above will fix it, but I suspect change to `xhook` will be a better solution long term.

**Comment by Nyratas** [comment]
Hi @flxsource,

Indeed, if the issue is caused by another package, I'd suggest opening an issue there.

Thanks for reporting this!

**Comment by flxsource** [comment]
For anyone else with this issue, the issue raised with xhook is [here](https://github.com/jpillora/xhook/issues/104)
