### ISSUE TITLE
Simple array items field without layout complexity

### ISSUE THREAD

**Issue by hasnatwe** [whitecube/nova-flexible-content#279]
Thanks a lot for this plugin. Is there any way to use it for plain array items. Like following plain data without complex layout:
`['item 1', 'item 2', 'item 3', .....]`
So I just want to save only values, no layout. Just like this package https://github.com/dillingham/nova-items-field ??? Thanks

**Comment by Nyratas** [comment]
Hi @hasnatwe,

Yes, you could create your own resolver that would save the flexible's value in the format you desire and parse it back into the format the field requires for display. 

More info in [the docs](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes).
