### ISSUE TITLE
How to test nova-flexible-content with PHP Unit

### ISSUE THREAD

**Issue by msouto346** [whitecube/nova-flexible-content#293]
Hello, when I try to simulate a post request in my unit test I get this error as response:

`The given data was invalid. The field test.0.attributes.name is required`

I think it's due to the key being different each request. Any suggestion on how to test it? Thank you.

**Comment by voidgraphics** [comment]
I suggest using Laravel Dusk to test this package. Here is an example project with a dusk test suite that makes sure the flexible field works correctly: https://github.com/whitecube/nova-flexible-content-tests
