### ISSUE TITLE
Display flexible content in index view ?

### ISSUE THREAD

**Issue by ligne13** [whitecube/nova-flexible-content#304]
Hi,

how can I display flexible content in a column of the index view ?
Is there a callback to parse the JSON content and to display relevant values as a string ?

thanks

**Comment by phlisg** [comment]
You could use a field that only shows on the index view with `Field::make()->onlyOnIndex()`, for example:

```php
Text::make('some index field to show', 'random_unexisting_column')
    ->fillUsing(fn(Request $request, Model $model, $attribute) => null) // so nothing happens when you save the resource
    ->displayUsing(function($value, Model $model) {
        // dirty example:
        if (isset($model->flexibleColumn[0]) return $model->flexibleColumn[0]['attributes']['specific_field']); 
    })
    ->onlyOnIndex(),
```

Of course, you could use some method somewhere that treats your flexible attributes in your models to return whatever you want, here it just returns the first flexible value.

I use this technique quite often to further personalize the index view. It looks a bit chaotic in the Resource class but I haven't found something neater.
