### ISSUE TITLE
can I save a flat structure?

### ISSUE THREAD

**Issue by muni-oscar-parra** [whitecube/nova-flexible-content#305]
Congratulations in advance, this package is great.

it is possible to save a flat structure in json, currently it is saved like this

```
[
    {
        "key": "Q5WhajEpJ5IEY8KU",
        "layout": "field",
        "attributes": {
            "key": "unit_of_measure",
            "type": "string_nullable",
            "options": null
        }
    },
    {
        "key": "hEt2kcF9LPIYsGcH",
        "layout": "field",
        "attributes": {
            "key": "description",
            "type": "integer_nullable",
            "options": null
        }
    }
]
```

however I only have one layout and I want to save something like this

```
[
    {
        "key": "unit_of_measure",
        "type": "string_nullable",
        "options": null
    },
    {
        "key": "description",
        "type": "integer_nullable",
        "options": null
    }
]
```

it's possible?

**Comment by toonvandenbos** [comment]
Sorry for the delay, but as the answer above stated, you can indeed save the flexible values in the format you want when using a [custom resolver](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes).
