### ISSUE TITLE
How to use it flexible content with HasMany relationshio ?

### ISSUE THREAD

**Issue by scramatte** [whitecube/nova-flexible-content#306]
Hello,

How to use it flexible content with HasMany relationshio ? I've read in another post to use custom preset and resolver.
But I'm unable to found any example in the doc.

Can you some real life example of how to use preset/ resolver and  manage relationship?

Regards

**Comment by SanjinOsmanbasic** [comment]
Since no one answered you - I can point you to #309 where I have an example of this relationship - just disregard the nested Flexible field that I needed.

**Comment by Nyratas** [comment]
Hi @scramatte,

The example in the full docs does exactly what you're looking for (HasMany) : https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes
