### ISSUE TITLE
FlexibleCast returning a string

### ISSUE THREAD

**Issue by dinandmentink** [whitecube/nova-flexible-content#311]
I think I may be missing something obvious, but can't figure it out. 

I have an `Association` model, to which I have added a CTA layout:

```php
Flexible::make(trans("admin.ctas"), "ctas")
    ->button(trans("admin.cta"))
    ->addLayout(trans("admin.cta"), 'cta', [
        Text::make(trans("admin.title"), "title"),
        Text::make(trans("admin.link"), "link"),
        Select::make(trans("admin.color"), "color")
            ->options([
                "primary" => trans("admin.primary"),
                "secondary" => trans("admin.secondary"),
                "light" => trans("admin.light"),
                "dark" => trans("admin.dark"),
                "white" => trans("admin.white"),
            ]),
    ]),
```

In my `Association` model I use the `FlexibleCast`:

```
class Association extends Model
{
    protected $casts = [
        "ctas" => FlexibleCast::class,
    ];
}
```

Now, after saving some cta's the database holds this value in a json column, everything working as I would expect:

```
[{"key": "gZ16OPeItKGroBYo", "layout": "cta", "attributes": {"link": "/pages/contact", "color": "secondary", "title": "Contact"}}]
```

However, the cast doesn't seem to work. Because `Association::find(2)->ctas` returns to me the following `String`(!):

```
 "[{"key": "gZ16OPeItKGroBYo", "layout": "cta", "attributes": {"link": "/pages/contact", "color": "secondary", "title": "Contact"}}]"
```

It doesn't seem to be actually casting `ctas` to a collection of objects. Am I missing something? `json_decode`, or using `"json" as cast works as I would expect.

**Comment by Nyratas** [comment]
Hi @dinandmentink, did you try using [JSON casting](https://laravel.com/docs/8.x/eloquent-mutators#array-and-json-casting) just to see if all casts are not working or just the FlexibleCast ? Did you `use Whitecube\NovaFlexibleContent\Value\FlexibleCast;` ?

**Comment by dinandmentink** [comment]
Thanks for the response. Yes, json casting works as I would expect:

```
protected $casts = [
        "ctas" => "json",
    ];
```

```
>>> App\Models\Association::first()->ctas
=> [
     [
       "key" => "nlxDnMG2P8kGt73Z",
       "layout" => "cta",
       "attributes" => [
         "link" => "/pages/contact",
         "color" => "primary",
         "title" => "Contact",
       ],
     ],
   ]
```

Also, yes confirm I am using `Whitecube\NovaFlexibleContent\Value\FlexibleCast;`:

```
protected $casts = [
    "ctas" => \Whitecube\NovaFlexibleContent\Value\FlexibleCast::class,
];
```


```
>>> App\Models\Association::first()->ctas
=> "[{"key": "nlxDnMG2P8kGt73Z", "layout": "cta", "attributes": {"link": "/pages/contact", "color": "primary", "title": "Contact"}}]"
```

**Comment by Nyratas** [comment]
Inside the `HasFlexible` trait (which we're using in `FlexibleCast`) we're returning the raw value (string) when in the following context :

```php
if(app()->getProvider(NovaServiceProvider::class) && !app()->runningInConsole() && !app()->environment('testing')) {
    return $value;
}
```

In other words, if you're testing inside Nova itself it won't return the casted value (because the field will take care of it by itself). Is that your case ?

**Comment by dinandmentink** [comment]
Ah,  yes, thanks, this is the case. This helps a lot, thanks.

**Comment by ramunasartme** [comment]
I have the same issue. How to solve?

**Comment by TijmenWierenga** [comment]
@toonvandenbos I'm running into issues with casting as well due to the raw value being used in all contexts.

I'm in the situation where I have Nova installed in my application which is also exposing an API. This means the `NovaServiceProvider` is always there so my API will never cast into layouts.

Am I doing something wrong or is this by design?
