### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by jphms** [whitecube/nova-flexible-content#32]
Not a bug per se, just a suggestion. I'm using this package in a project and the client just complained that the delete button is too close to the move up/down arrows, and that it prompts no dialog when clicked, leading to deleting things by accident (which happened). Anyway, just a suggestion for a small UX improvement. If you accept PRs I can probably make one with a javascript confirmation dialog. As of now (and probably this month), I don't have enough time for a fancier modal.

**Comment by Nyratas** [comment]
Hi @jphms,

That's indeed a good idea. Would be happy to accept a PR for this.
If you feel like it, please keep it as simple as possible, with the confirmation button as close as possible to the delete button. Maybe something like this:

![confirm](https://user-images.githubusercontent.com/5635557/59269952-8d746a80-8c50-11e9-95ab-30b1b86c4045.png)

**Comment by jphms** [comment]
Alright. Had a look at the code and it seems fairly easy to implement. Might take me a couple days, though. Short on free time these days. 👍

**Comment by jphms** [comment]
Just to give some update. I've been terribly busy, but I still plan to do this.

**Comment by onemoreahmad** [comment]
I've done this on my fork, but have no idea how to do a PR with a new branch https://github.com/onemoreahmad/nova-flexible-content/commit/9ff6132764dd08c9c674ee9c6dc9fe2fae865610

<img width="258" alt="Screen Shot 2019-07-09 at 8 29 23 AM" src="https://user-images.githubusercontent.com/1885785/60862468-4e710f00-a226-11e9-8cb7-ae0c61018fed.png">
<img width="166" alt="Screen Shot 2019-07-09 at 8 29 34 AM" src="https://user-images.githubusercontent.com/1885785/60862469-4e710f00-a226-11e9-9426-1c040f5819f1.png">
<img width="249" alt="Screen Shot 2019-07-09 at 8 30 07 AM" src="https://user-images.githubusercontent.com/1885785/60862470-4e710f00-a226-11e9-9ac5-c4be3835d719.png">
<img width="423" alt="Screen Shot 2019-07-09 at 8 30 29 AM" src="https://user-images.githubusercontent.com/1885785/60862471-4f09a580-a226-11e9-9c0e-2681170119c7.png">

**Comment by voidgraphics** [comment]
Closed with the merge of #43
