### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by schonhoff** [whitecube/nova-flexible-content#323]
Hello,

will there be an update for Laravel 9 support?
Thanks for the awesome package!

**Comment by schonhoff** [comment]
Hello,

thanks for the answer. Most packages (specially Nova packages) can be updated to Laravel 9. Maybe you can create a Laravel 9 major tag with the info that it is not tested. You are the last package in my 45 packages that is not Laravel 9 compatible. The most changes (except Synfony and the Flysystem) where already delivered in Laravel 8 and shouldn't break anything. Maybe you can do it and hopefully someone can fit the maintainer gap. I'm not so confident with your package, that I can do it (sadly).

Thanks again for the great package.

**Comment by ahinkle** [comment]
We have been testing on Laravel 9. We don't see any problems. Are you having any problems, @schonhoff?

**Comment by voidgraphics** [comment]
v2.9.0 now allows upgrades to Laravel 9. Thank you @ahinkle for testing.
