### ISSUE TITLE
PHP 8.1 support?

### ISSUE THREAD

**Issue by mabdullahsari** [whitecube/nova-flexible-content#333]
Hey 👋🏼

I was going to submit a PR to add PHP 8.1 support, but it seems like the package support is going back as far as 7.2 which is really old now.

Like, the package works fine on 8.1, but `php-fpm` gets hammered with deprecation notices which can easily be fixed by adding return types to internal functions or the `#[ReturnTypeWillChange]` attribute. Unfortunately, this cannot be "fixed" unless < 8 support is dropped.

Are there any future plans to drop support for older PHP versions? At least those prior to version 8 which Laravel 9 also did drop?

Thank you!

**Comment by ConsoleTVs** [comment]
Came here to say the same. PHP 8.1 drops heavy deprecation warnings.

**Comment by HenriqueSPin** [comment]
#370

**Comment by mabdullahsari** [comment]
Sorry for not returning in time. 

I actually attempted a proper 8.1 migration without the #[ReturnTypeWillChange] attribute, but ended up in a complete uncharted labyrint not knowing what to do in many scenarios due to the lack of tests (unfortunately).

Since an attribute PR has been merged for the meantime, I'm closing this issue.

@HenriqueSPin Thanks
