### ISSUE TITLE
Undefined property: stdClass::$layout"

### ISSUE THREAD

**Issue by ikramooe** [whitecube/nova-flexible-content#348]
i am getting this error 
C:\\xampp\\htdocs\\e-commerce\\vendor\\whitecube\\nova-flexible-content\\src\\Value\\Resolver.php"

i'm using laravel 6 
and nova flexible content 0.2.2

**Comment by toonvandenbos** [comment]
This package is not compatible with Laravel 6, please update to a recent version of Laravel.
