### ISSUE TITLE
Css class conflict with outl1ne/nova-multiselect-field package

### ISSUE THREAD

**Issue by rasmuscnielsen** [whitecube/nova-flexible-content#356]
The new v1.0.0 seems to re-introduce previous issues reported in #137 due to the `@vueform/multiselect` dependency targeting global `.multiselect` class.

Before update:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/8465957/170466274-b29ea971-750b-4b57-88af-3df08853391d.png">

After update:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/8465957/170466334-c9e3bcf0-e83c-4b01-9ed5-58f4e02092f5.png">

**Comment by mstaack** [comment]
yeah same for me with `outl1ne/nova-multiselect-field`

**Comment by crezra** [comment]
+1 on this issue
