### ISSUE TITLE
Upgrade guide for Nova 4

### ISSUE THREAD

**Issue by baszach** [whitecube/nova-flexible-content#363]
Hi,

I have upgraded this package to version `1.0` but I'm still seeing weird behavior on the `Flexible` field.
Examples:
- I can't delete an entry, only add
- The casting is not working anymore

Is there some kind of upgrade guide or a changelog where I can understand what changed?

Also, has this happened to someone else? I couldn't find another issue like that.

**Comment by hoczeus** [comment]
I have this problem since Nova v4

- The casting is not working anymore

**Comment by toonvandenbos** [comment]
Hi @baszach,

Did you publish the latest assets ? 

Regarding the casting issue, do you mean casting when using the field's value outside of Nova (in your application) ? If so, do you have an error to share ?

**Comment by baszach** [comment]
The casting error was a Laravel related error. I have fixed that. Upgrade from 8.x to 9.x needed some null-checks at casting.

Yes. I published the assets. Here's how the flexible field looks for me :/
![image](https://user-images.githubusercontent.com/47082864/179530198-b27be319-3e12-407b-bd3c-c547c6d47f3f.png)

Can I share something with you that would help you?

**Comment by toonvandenbos** [comment]
Can you open a new issue explaining the specific problems with nova-tabs when you're ready ? Thanks.

**Comment by atmediauk** [comment]
> > Can you explain what the display problem is ? Since we're only viewing a portion of the UI, I'm not sure what I'm looking at.
> 
> I cannot remove entries. There's no trash can etc.
> 
> > Which version of Nova are you using? Are there errors in the JavaScript console?
> 
> 4.12.2 and I have this warning: **This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!** but no error.
> 
> I just realized that my `Flexible` field works fine on it's own. But in most of my admin panel it is inside a tab (see [nova-tabs](https://github.com/eminiarts/nova-tabsl)). I found that only in this case it's broken. I'll have to dive deeper here.

I was just porting over a nova 3 app (working) to 4 and came across the same issue. I'm not using nova tabs though. The collapse, delete, move up/ down etc are not visible. Unfortunately no errors are being thrown either. Items are being added correctly though. 

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/4824454/184908568-7c9f588c-a128-4cf1-ba08-11c4631f3e94.png">
