### ISSUE TITLE
Store SimpleRepeatable under Flexible Content not working

### ISSUE THREAD

**Issue by chirag-nandaniya** [whitecube/nova-flexible-content#369]
I am using SimpleRepeatable under Flexible Content Layout. Its generates the fields but not able to save it successfully. I think issue is SimpleRepeatable itself generate a JSON and not generate any attribute.

Flexible::make('Sub Regions', 'sub_regions')
->addLayout('Sub Region', 'sub_region', [
Text::make('Title'),
SimpleRepeatable::make('Charges', 'charges', [
Text::make('Weight From', 'weight_from')
->required(true),
Text::make('Weight To', 'weight_to')
->required(true),
])
->fullWidth()
->button('Add Sub Region'),
]),

Able to create one JSON attribute and save SimpleRepeatable JSON under it? Here "Charges" attribute not generated.

**Comment by toonvandenbos** [comment]
Use another `Flexible` field instead of `SimpleRepeatable` and it should work fine.
