### ISSUE TITLE
Call to a member function getMedia() on array

### ISSUE THREAD

**Issue by iventru** [whitecube/nova-flexible-content#37]
I use "Ebess\AdvancedNovaMediaLibrary" for images gallery and got error: Call to a member function getMedia() on array

Code:

 Flexible::make('Gallery')
                ->addLayout('Simple content section', 'wysiwyg', [
                    Images::make('Computer case', 'computer-image-case')
                        ->conversionOnIndexView('thumb')
]

Flexible without Images::make work fine. Images::make without Flexible work fine.

**Comment by voidgraphics** [comment]
Duplicate of #33
