### ISSUE TITLE
Error whene saving  a layout data

### ISSUE THREAD

**Issue by MA7MOUDAL3RABY** [whitecube/nova-flexible-content#383]
Too few arguments to function Whitecube\NovaFlexibleContent\Layouts\Layout::setAttribute(), 1 passed in D:\Work\www\Araby\Araby\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php on line 1000 and exactly 2 expected

**Comment by voidgraphics** [comment]
Never encountered this, please provide an example so we can reproduce the error.

**Comment by MA7MOUDAL3RABY** [comment]
this error apears when using Heading::make('')->asHtml()

it is working on nova 3
crash on nova 4
