### ISSUE TITLE
Flexible returns null

### ISSUE THREAD

**Issue by martin-ro** [whitecube/nova-flexible-content#39]
Hi, I'm trying to get this package work on multilingual setup but in my views the content returns `null`.

Packages used: 
```
"mrmonat/nova-translatable": "^2.0",
"spatie/laravel-translatable": "^4.1",
"whitecube/nova-flexible-content": "dev-master"
```

Page model:
```
<?php

namespace App\Models;

use App\Nova\Flexible\Layouts\IntroBlockLayout;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;
use Whitecube\NovaFlexibleContent\Concerns\HasFlexible;

class Page extends Model
{
    use HasSlug, HasTranslations, HasFlexible;

    /**
     * Sets table name.
     *
     * @var string
     */
    protected $table = 'pages';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'slug',
        'content',
    ];

    /**
     * The attributes that are translatable.
     *
     * @var array
     */
    public $translatable = [
        'title',
        'slug',
        'content',
    ];

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions()
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getFlexibleContentAttribute()
    {
        return $this->flexible('content', [
            'introblock' => IntroBlockLayout::class,
        ]);
    }
}

```

Custom layout (IntroBlockLayout):

```
<?php

namespace App\Nova\Flexible\Layouts;

use MrMonat\Translatable\Translatable;
use Whitecube\NovaFlexibleContent\Layouts\Layout;

class IntroBlockLayout extends Layout
{
    /**
     * The layout's unique identifier
     *
     * @var string
     */
    protected $name = 'introblock';

    /**
     * The displayed title
     *
     * @var string
     */
    protected $title = 'Intro Block';

    /**
     * Get the fields displayed by the layout.
     *
     * @return array
     */
    public function fields()
    {
        return [
            Translatable::make('title'),
            Translatable::make('text'),
        ];
    }

}
```

View show.blade.php:
```
{{ $page->flexible('introblock') }}
{{ $page->getFlexibleContentAttribute() }}
```

Content field in DB:
```
{"en": [{"key": "dadcc3bbc6104575", "layout": "introblock", "attributes": {"text": {"da": "Da Text", "de": "De Text", "en": "En Text"}, "title": {"da": "Da title", "de": "De title", "en": "En title"}}}]}
```

both attempts to render the content in the view return null. Any idea what I'm doing wrong here?

**Comment by voidgraphics** [comment]
I'm guessing the `$page->flexible('introblock')` call does not know which lang key to look into within the stored json. 

I see that you're using translatable fields for the text inputs within the layout which is great, but it means you do not need to make the `content` attribute translatable itself. Try removing `content` from the `translatable` array on your model.

**Comment by Nyratas** [comment]
Hi @martin-ro,

First of all, I think you used the wrong attribute in the first render attempt.

```
{{ $page->flexible('introblock') }}
```

Should be

```
{{ $page->flexible('content') }}
```

But indeed, the flexible content should'nt be the translated field. It should contain translated fields. Please take a look at the explanation given in [this issue](https://github.com/whitecube/nova-flexible-content/issues/7). Hope it helps! :)

**Comment by martin-ro** [comment]
Thanks for the fast reply. I found that issue you mention earlier and that's why I setup my custom layout "IntroBlockLayout" containing translated fields. That is what I understand by "inside flexible fields". 

What I mean is, here in my Nova Page model:
```
...
Flexible::make('Content')
                ->addLayout(IntroBlockLayout::class),
...
```
A flexible field, containing (via IntroBlocklayout):
```
...
public function fields()
    {
        return [
            Translatable::make('title'),
            Translatable::make('text'),
        ];
    }
...
```

Is that not how to setup translatable fields inside the flexible layout?

**Comment by voidgraphics** [comment]
> Is that not how to setup translatable fields inside the flexible layout?

Yes, it is 😄 the problem is you also made the whole flexible a translated field by doing:

```php
    /**
     * The attributes that are translatable.
     *
     * @var array
     */
    public $translatable = [
        'title',
        'slug',
        'content',
    ];
```

That's the problem. Flexible fields themselves should not be translatable, only the subfields can be.

So, you should have this instead:

```php
    /**
     * The attributes that are translatable.
     *
     * @var array
     */
    public $translatable = [
        'title',
        'slug',
    ];
```

**Comment by martin-ro** [comment]
Ah thanks, totally didn't see making it translatable on the model. thanks!

**Comment by gwleuverink** [comment]
Hi all! First of all; thanks for the amazing package! 

That said, I have the same issue, but in our case I need to make the entire field translatable so different locales may have a different combination of flexible layouts.

I've dug through all issues but have only found solutions using translatable fields inside flexible layouts.
We're using https://github.com/DigitalCloud/multilingual-nova, which gives us a language selector for the entire resource. 

Using the suggested package by mrmonat we whould also have to select a language for each translatable field inside the layout, which ignores the set language by the aforementioned multilingual-nova package.

Is there any other way to get this to work? Any help is much appreciated!

**Comment by gwleuverink** [comment]
Hi! Sorry I didn't notice this was closed. I'll open a new issue

**Comment by gwleuverink** [comment]
@martin-ro Got it working with the example in #44. Is this of any use to you?
