### ISSUE TITLE
LaravelNova is not defined

### ISSUE THREAD

**Issue by Kubitomakita** [whitecube/nova-flexible-content#391]
After upgrading Nova to 4.15.0.

The error can be seen in console right after accessing Nova, nothing renders in the body

The issue has been introduced in version 1.0.3, it works in 1.0.2

![image](https://user-images.githubusercontent.com/18362490/191470517-2fa9850d-05db-47ac-8986-36b4eb40ffc2.png)

**Comment by voidgraphics** [comment]
Sounds related to #387, @mikaelpopowicz do you know what could cause this?

**Comment by mikaelpopowicz** [comment]
Hi @voidgraphics I'll investigate

**Comment by mikaelpopowicz** [comment]
Hi @Kubitomakita 

You may run the `php artisan nova:publish` command to publish the missing `public/vendor/nova-kit/nova-packages-tool` folder.

In addition you add the following command under script.post-autoload-dump in your application's composer.json file :

```json
{
  "script" : {
    "post-autoload-dump": [
      "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
    ]
  }
}
```

**Comment by KasparRosin** [comment]
@Kubitomakita Also make sure that your `public/vendor/` folder is not ignored.

I had that issue few weeks ago, where I had published the assets, but because I was not specifying which vendor folder to ignore, it was ignoring all vendor folders in the probject, including the one in `public/vendor`

**Comment by Kubitomakita** [comment]
@mikaelpopowicz @KasparRosin sorry for the late response. It doesn't work, we're already publishing this package. Assets from  `nova-kit/nova-packages-tool` simply doesn't publish.

![image](https://user-images.githubusercontent.com/18362490/196153777-97d41c4c-262d-4636-ac12-b57c9a79ef84.png)

It might be because your package is loaded by another Laravel package, like this:
App <- Package X <- Nova Flexible Content

**Comment by mikaelpopowicz** [comment]
Hi @Kubitomakita 

Thank you for the report.

It's weird because the `NovaKit\NovaPackagesTool\LaravelServiceProvider::class` should be autoloaded by the auto discover package command.
