### ISSUE TITLE
Add ability to expand/collapse layout instances

### ISSUE THREAD

**Issue by voidgraphics** [whitecube/nova-flexible-content#4]
It could be nice to be able to collapse existing layout instances to make them take less space in the page if we're not currently editing them.

**Comment by nilsE** [comment]
yes, please...!

**Comment by GarethSomers** [comment]
I've made a basic start on this here: https://github.com/whitecube/nova-flexible-content/pull/59

**Comment by Nyratas** [comment]
This has been merged & will be released in v.0.1.10.
