### ISSUE TITLE
Undefined property: {Layout}::$exists

### ISSUE THREAD

**Issue by Nks** [whitecube/nova-flexible-content#402]
After updating Laravel to v9.35.0 I got the error:

```Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php
:467
```

The "error" coming from Laravel Framework by [this method](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L465) was added recently.

Possible fix:

Add the following variables to class "Whitecube\NovaFlexibleContent\Layouts\Layout":

```
protected $exists = false;

protected $wasRecentlyCreated = false;
```

**Comment by 1stevengrant** [comment]
seeing this one too

**Comment by Nks** [comment]
@1stevengrant, you can use fork as a temporary fix:

Add 
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Nks/nova-flexible-content.git"
        }
    ],
``` 

to your composer.json file and add

```"whitecube/nova-flexible-content": "dev-develop",``` as the dependency.

**Comment by voidgraphics** [comment]
Just tagged `v1.0.5` with your fix, thanks!
