### ISSUE TITLE
you tagged the last release as the wrong version syntax

### ISSUE THREAD

**Issue by Slgoetz** [whitecube/nova-flexible-content#428]
The newest release is tagged as [v0.2.14](https://github.com/whitecube/nova-flexible-content/releases/tag/v0.2.14), however, the one prior to that is [v1.0.6](https://github.com/whitecube/nova-flexible-content/releases/tag/v1.0.6). This means your new syntax of adding a 0 in the beginning made it so that its never satisfied as it is a lower version number. 

Can you please update it to follow the same syntax of - v2.14

**Comment by voidgraphics** [comment]
Hello, the version numbers are correct. We currently support and release bug fixes for both the v0.x and the v1.x versions, the difference being which versions of Laravel Nova they support.

For Nova 3, use v0.x releases, and for Nova 4, use v1.x releases.

**Comment by Slgoetz** [comment]
Thank you for the clarification
