### ISSUE TITLE
Translatable support (without mrmorat/nova-translatable)

### ISSUE THREAD

**Issue by gwleuverink** [whitecube/nova-flexible-content#44]
Hi all! First of all; thanks for the amazing package!

We're trying to get this package to work with https://github.com/DigitalCloud/multilingual-nova, which gives us a language selector for the entire Nova resource.

I've seen a couple issues suggesting mrmorat's translatable fields inside the flexible layout. Sadly I need to make the entire field translatable so different locales may have a different combination of flexible layouts.

Using the suggested package by mrmonat we would also have to select a language for each translatable field inside the layout. Using this in conjunction with the aforementioned multilingual-nova package doesn't make much sense from a UX consistency standpoint.

Is there any other way to get this to work? Any help is much appreciated!

**Comment by gwleuverink** [comment]
I believe we fixed it. The problem was the content accessor that called the flexible() method. It doesn't play nice in conjunction with laravel-translatable.

The content accessor itself is really convenient. By assigning it a different name & altering it a little bit we can make it work with Spatie translatable.

Assuming the situation in the example below the Flexible nova field is assigned to the `$page->content` property. But when using the data in your views you should use `$page->flexible_content` (accessor only)

``` php
class Page extends Model
{
    use HasTranslations;
    use HasFlexible;

    /**
     * All transaltable properties.
     *
     * @var array
     */
    public $translatable = [
        'title', 'meta_title', 'meta_description', 'title', 'content',
    ];

    /**
     * All properties that need to be appended when serialised.
     *
     * @var array
     */
    protected $appends = [
        'flexible_content',
    ];

    /**
     * Format flexible content.
     *
     * Note that this should not be named getContentAttribute
     * Or else then Nova resource won't load the data correctly.
     */
    public function getFlexibleContentAttribute()
    {
        $flexible = $this->getTranslation('content', $this->getLocale());

        if (app()->getProvider(NovaServiceProvider::class)) {
            return $flexible;
        }

        return $this->toFlexible($flexible ?: null);
    }
}
```

**Comment by Nyratas** [comment]
Hi @gwleuverink,

Glad you got it working like this. 

The following part could be used in the `HasFlexible` trait and save other users from a few headaches :

```
        if (app()->getProvider(NovaServiceProvider::class)) {
            return $flexible;
        }
```

Thanks  for sharing!

**Comment by jornwildenbeest** [comment]
Hi,

Iknow this is an old closed issue but I can't figure out how to get this to work.
When i try to do this i get the this error:
`Undefined property: stdClass::$layout {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$layout at .../vendor/whitecube/nova-flexible-content/src/Value/Resolver.php:42)`
