### ISSUE TITLE
Bug: Undefined array key "attributes" - Concerns/HasFlexible.php line 122

### ISSUE THREAD

**Issue by m-lotze** [whitecube/nova-flexible-content#441]
The line 122 in Concerns/HasFlexible.php creates an error when the array key `attributes` is not set:

```
$attributes = (array) $item['attributes'] ?? [];
```

it should be:

```
$attributes = (array) ($item['attributes'] ?? []);
```

See my pull request for a fix.

**Comment by toonvandenbos** [comment]
Indeed. PR merged, thanks!
