### ISSUE TITLE
Validation on layouts not working 

### ISSUE THREAD

**Issue by PaulLawton227** [whitecube/nova-flexible-content#452]
Nova:  3.32
whitecube/nova-flexible-content:  0.2.13

My Fields array:
`Text::make('Test', 'test')->rules('required'),`
`Flexible::make('Opt Ins', 'fields')`
`    ->button('Add Opt In')`
`     ->addLayout('Opt In', 'opt_ins', [`
`       Text::make('Opt In Handle', "opt_in_handle")->rules('required'),`
`       Text::make('Opt In Description'),`
`    ]),`
The validation on the root 'Test' field works - but nothing triggers on submit for the layout field (apart from adding the red star to the required fields)

<img width="889" alt="image" src="https://user-images.githubusercontent.com/37216686/228474757-058aa183-20db-4f46-8163-fb76dbef235e.png">

**Comment by PaulLawton227** [comment]
Not a bug - turns out is was an issue with using DigitalCreative\JsonWrapper to wrap the fields with.
using Naoray/nova-json wrapper instead fixed the issue.

**Comment by Kristories** [comment]
Hey @PaulLawton227 can you show us how to solve this using Naoray/nova-json?
