### ISSUE TITLE
Random key insertion into JSON array

### ISSUE THREAD

**Issue by BenySLO** [whitecube/nova-flexible-content#47]
when i save my resource i expect the flexible to save like that: 

> [{"layout":"links","key":"112be2b576879837","attributes":{"title":"eARO","link":"https://www.test.com/"}},
{"layout":"links","key":"a0mtwyx2jrtwaou2f3jlo-links","attributes":{"title":"eAIP","link":"https://www.test2.com/"}}]

but when i save the flexible i get this:

> [{"layout":"links","key":"112be2b576879837","attributes":{"112be2b576879837__112be2b576879837__title":"eARO","112be2b576879837__112be2b576879837__link":"https://www.test.com/"}},{"layout":"links","key":"a0mtwyx2jrtwaou2f3jlo-links","attributes":{"a0mtwyx2jrtwaou2f3jlo-links__a0mtwyx2jrtwaou2f3jlo-links__title":"eAIP","a0mtwyx2jrtwaou2f3jlo-links__a0mtwyx2jrtwaou2f3jlo-links__link":"https://www.test2.com/"}}]

Now i know the problem is here when i use NovaDependencyContainer:
```
public function fields(Request $request) {
	return[
		NovaDependencyContainer::make([
			Flexible::make('Value')->addLayout('Links', 'links', [
				Text::make('Title'),
				Text::make('Link'),
			]),
		])->dependsOn('type', 'outer_FE_links_array'),
	];
}
```
if i just use the flexible field as an normal field it works:
```
public function fields(Request $request) {
	return[
		Flexible::make('Value')->addLayout('Links', 'links', [
			Text::make('Title'),
			Text::make('Link'),
		]),
	
	];
}
```
any suggestions how to solve that ?

**Comment by Lotfull** [comment]
Additionally I can say that this bug appears only when you switch to this Flexible twice or more. And `key` value appends to the flexible fields keys as many times,  as you switch to it using NovaDependencyContainer.

**Comment by fenestron** [comment]
I solved this problem by checking for the presence of a key in the attribute. 
You can see the solution to the problem in this commit - https://github.com/Lotfull/nova-flexible-content/commit/7f24b4a98bf5b379e0fd0a6491d1ed7460db5ffc

**Comment by BenySLO** [comment]
> I solved this problem by checking for the presence of a key in the attribute.
> You can see the solution to the problem in this commit - [Lotfull@7f24b4a](https://github.com/Lotfull/nova-flexible-content/commit/7f24b4a98bf5b379e0fd0a6491d1ed7460db5ffc)

well it only works if i change the function to : 
```
   value: function renameFields() {
            for (var i = this.fields.length - 1; i >= 0; i--) {      
                  this.fields[i].attribute =  this.fields[i].attribute;
            }
        }
```
But since I'm working on a live project i cannot change the  function in vendor others wont see the change.

**Comment by Nyratas** [comment]
Hi,

Thanks for reporting this. I will take a closer look into this as soon as possible. 

It is indeed important we try to keep this field as compatible as possible with other fields. However, keep in mind that in some cases, opening an issue on the other package's repository could be a better solution, especially if it would require dirty workarounds on this package's end.

**Comment by Nyratas** [comment]
Could somebody please check if this issue is still relevant since the latest release, v0.1.10? Thanks!

**Comment by BenySLO** [comment]
@Nyratas as for now without changing anything and if i replicate my first problem

1. using this flexible field as standalone it works, 

2. if I add flexible into the _NovaDependencyContainer_ I get Array to string conversion error. If I have more time I'll let you know why this is happening. Probably need to make a custom resolver for that to work.

**Comment by BenySLO** [comment]
I will close this issue, If the problem persists I will reopen it.
