### ISSUE TITLE
Delete layout error <danger-button>

### ISSUE THREAD

**Issue by beebmx** [whitecube/nova-flexible-content#489]
Since 4.28.x of Laravel Nova, in the confirm panel to delete the layout, it doesn't work.

![2023-11-20 at 6  58 44@2x](https://github.com/whitecube/nova-flexible-content/assets/2191576/0c41ca1d-09c4-4504-8533-9814f6d695a9)

It looks like <danger-button> component is not rendering.

**Comment by stefano-ciotola** [comment]
I'm experiencing the same issue since updating to Laravel Nova 4.28.x.
The delete button is not functioning properly, it seems like the component isn't rendering correctly.
Has someone found a workaround / fix for this?
