### ISSUE TITLE
Value Resolver does not understand Collections

### ISSUE THREAD

**Issue by tpetry** [whitecube/nova-flexible-content#49]
The `Whitecube\NovaFlexibleContent\Value\Resolver` resolvers `extractValueFromResource` method does at the moment only handle strings and arrays. But eloquent models also have the ability to represent an array with the collection accessor, which is just an encapsulated array but php's `is_array` function will be false. The simple solution would be to check for collections and use their array value:

```
if($value instanceof Collection) return $value->toArray();
```

**Comment by voidgraphics** [comment]
Thanks for reporting this and the suggested solution @tpetry.

Can you maybe try using the `dev-master` version to check if the fix does the trick for you? 👍

**Comment by tpetry** [comment]
It will work, its the exact same change i done locally

**Comment by voidgraphics** [comment]
Sweet. It will be included in the next release [`v0.1.8`](https://github.com/whitecube/nova-flexible-content/releases/tag/untagged-5a81169e2ddaa2614d4d).
