### ISSUE TITLE
Question: Is it possible to create a form for several entities using this package?

### ISSUE THREAD

**Issue by batFormat** [whitecube/nova-flexible-content#5]
Please tell me, is it possible to create a form for several entities using this package?

For example, Books and Authors?

**Comment by Nyratas** [comment]
Hi @batFormat,

I'm not sure to understand your question completely. Do you want to be able to edit a _Many to Many_ relationship between Books and Authors?

If that's the case, yes that is totally possible. You'll need to create a custom [preset](https://whitecube.github.io/nova-flexible-content/#/?id=predefined-preset-classes) and a [resolver](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes).

How these classes will work together depends on what you're trying to achieve. Do you need to edit fields on the pivot table or do you _just_ want to attach authors to books? I can give you an example for both cases if you tell me what you're interested in.

**Comment by batFormat** [comment]
@Nyratas I want to attach authors to books.

**Comment by Nyratas** [comment]
Alright, here is a quick explanation on how to do this. I did not test this code, but it should show you how to get there.

You'll need a custom preset class, which will be used to attach a layout (= a repeatable group of fields) containing dynamic values coming from the database:

```php
use App\Author;
use Laravel\Nova\Fields\Select;
use Whitecube\NovaFlexibleContent\Flexible;
use Whitecube\NovaFlexibleContent\Layouts\Preset;

class AuthorsChoicePreset extends Preset
{

    /**
     * The available authors
     *
     * @var Illuminate\Support\Collection
     */
    protected $authors;

    /**
     * Create a new preset instance
     *
     * @return void
     */
    public function __construct()
    {
        $this->authors = Author::orderBy('lastname')->orderBy('firstname')->get();
    }

    /**
     * Execute the preset configuration
     *
     * @return void
     */
    public function handle(Flexible $field)
    {
        $field->hideFromIndex();
        $field->button('Add author');

        // First let's format the authors collection into an array [id => name]
        $authors = $this->authors->reduce(function($values, $author) {
            $values[$author->id] = $author->lastname . ' ' . $author->firstname;
            return $values;
        }, []);

        // Now we'll create the layout featuring a Select containing all thos authors
        $field->addLayout('Book author', 'author_layout', [
            Select::make('Author', 'author_select')
                ->options($authors)
                ->displayUsingLabels()
        ]);

        // Then attach a custom resolver that will take car of the real database relationship
        $field->resolver(\App\Nova\Flexible\Resolvers\AuthorsChoiceResolver::class);
    }
}
```

In this example we're using a basic `Select` field, but you could (and probably should) use another kind of field which will allow to search for a specific author.

As you can see, we're also attaching a `resolver` to the field. This class will `set` and `get` the Flexible's value in the database. Again, this is only an untested simple example:
```php
use Whitecube\NovaFlexibleContent\Value\ResolverInterface;

class AuthorsChoiceResolver implements ResolverInterface
{
    /**
     * get the field's value
     *
     * @param  mixed  $resource
     * @param  string $attribute
     * @param  Whitecube\NovaFlexibleContent\Layouts\Collection $layouts
     * @return Illuminate\Support\Collection
     */
    public function get($resource, $attribute, $layouts)
    {
        // First we'll fetch the authors linked to the resource
        $authors = $resource->authors()->get();

        // Now we'll map them into the "Book author" layout
        return $authors->map(function($author, $key) use ($layouts) {
            $layout = $layouts->find('author_layout');

            // Using duplicateAndHydrate, we'll create a copy of the original
            // Layout and fill it with the current author's data
            return $layout->duplicateAndHydrate($key, ['author_select' => $author->id]);
        });
    }

    /**
     * Set the field's value
     *
     * @param  mixed  $model
     * @param  string $attribute
     * @param  Illuminate\Support\Collection $groups
     * @return string
     */
    public function set($model, $attribute, $groups)
    {
        $class = get_class($model);

        // We'll only attach the related authors after the model
        // has been saved for the first time
        $class::saved(function ($model) use ($groups) {
            // Reduce the collection of hydrated layouts to an array 
            // only containing author IDs from the select field
            $authors = $groups->pluck('author_select')->all();

            // Sync the author IDs with the current model
            $model->authors()->sync($authors);
        });
    }
}
```

Last but not least, let's apply our preset (which includes the resolver configuration) to the Flexible field on the `Book` resource:
```php
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            Flexible::make('Authors')->preset(AuthorsChoicePreset::class)
        ];
    }
```

And that's it. You should have a Flexible field with a single repeated Layout containing a `Select` listing all available authors.

Honestly, even if it should work, I think this kind of setup would only be really (_really, really_) useful if the layout also included other fields (managing values on the pivot table for example). In this simple case, the pre-existing BelongsToMany field would probably be easier to use.

Let me know if this helps!

**Comment by muzafferdede** [comment]
Amazing work! Would be great if this sample was in docs as well. Things are a bit advance to understand. Examples like this simple is much easy to understand. Thankfully i found this to get an idea how it would be like. Thanks
