### ISSUE TITLE
Unable to parse incoming Flexible content, data should be an array.

### ISSUE THREAD

**Issue by yassir3wad** [whitecube/nova-flexible-content#58]
I have this error when saving the resource:
`
exception: "Exception"
file: "G:\laravel\headless\vendor\whitecube\nova-flexible-content\src\Flexible.php"
line: 268
message: "Unable to parse incoming Flexible content, data should be an array."
`

my fields:
`public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Flexible::make('Content')
                ->addLayout('Simple content section', 'wysiwyg', [
                    Text::make('Title'),
                    Markdown::make('Content')
                ])
                ->addLayout('Video section', 'video', [
                    Text::make('Title'),
                    Image::make('Video Thumbnail', 'thumbnail'),
                    Text::make('Video ID (YouTube)', 'video'),
                    Text::make('Video Caption', 'caption')
                ]),
        ];
    }`

request payload:
![image](https://user-images.githubusercontent.com/31948375/63217910-59895a00-c157-11e9-8a4b-4443cccd4a44.png)

model:
`class Page extends Model
{
    protected $fillable = [ 'content'];

    protected $casts = [
        'content' => 'array'
    ];
}`
nova version: 2.0.11
laravel version: 5.8.32

**Comment by yassir3wad** [comment]
@Nyratas

**Comment by Nyratas** [comment]
@yassir3wad could you provide a stack trace?

Also, could you open `G:\laravel\headless\vendor\whitecube\nova-flexible-content\src\Http\Middleware\InterceptFlexibleAttributes.php` and add `info($request->all());` on line `29` and show the output in your log file here? Thanks!

**Comment by jackabox** [comment]
@yassir3wad had this issue recently, required updating to the latest version of nova, and republishing assets to ensure that it worked, as seen at [https://nova.laravel.com/docs/2.0/installation.html#updating-nova](https://nova.laravel.com/docs/2.0/installation.html#updating-nova)

**Comment by mrbuku** [comment]
I agree with @jackabox response. Solved the same issue by updating my nova

**Comment by yassir3wad** [comment]
@mrbuku @jackabox sorry, I published the assets again, but the problem still exists.

@Nyratas 
Stacktrace:
`{
    "message": "Unable to parse incoming Flexible content, data should be an array.",
    "exception": "Exception",
    "file": "G:\\laravel\\headless\\vendor\\whitecube\\nova-flexible-content\\src\\Flexible.php",
    "line": 268,
    "trace": [
        {
            "file": "G:\\laravel\\headless\\vendor\\whitecube\\nova-flexible-content\\src\\Flexible.php",
            "line": 234,
            "function": "extractValue",
            "class": "Whitecube\\NovaFlexibleContent\\Flexible",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\whitecube\\nova-flexible-content\\src\\Flexible.php",
            "line": 220,
            "function": "syncAndFillGroups",
            "class": "Whitecube\\NovaFlexibleContent\\Flexible",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Fields\\Field.php",
            "line": 296,
            "function": "fillAttribute",
            "class": "Whitecube\\NovaFlexibleContent\\Flexible",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Fields\\Field.php",
            "line": 270,
            "function": "fillInto",
            "class": "Laravel\\Nova\\Fields\\Field",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\HigherOrderCollectionProxy.php",
            "line": 60,
            "function": "fill",
            "class": "Laravel\\Nova\\Fields\\Field",
            "type": "->"
        },
        {
            "function": "Illuminate\\Support\\{closure}",
            "class": "Illuminate\\Support\\HigherOrderCollectionProxy",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Collection.php",
            "line": 1120,
            "function": "array_map"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\HigherOrderCollectionProxy.php",
            "line": 61,
            "function": "map",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\FillsFields.php",
            "line": 67,
            "function": "__call",
            "class": "Illuminate\\Support\\HigherOrderCollectionProxy",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\FillsFields.php",
            "line": 35,
            "function": "fillFields",
            "class": "Laravel\\Nova\\Resource",
            "type": "::"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Http\\Controllers\\ResourceUpdateController.php",
            "line": 34,
            "function": "fillForUpdate",
            "class": "Laravel\\Nova\\Resource",
            "type": "::"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php",
            "line": 29,
            "function": "Laravel\\Nova\\Http\\Controllers\\{closure}",
            "class": "Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php",
            "line": 349,
            "function": "transaction",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php",
            "line": 237,
            "function": "__call",
            "class": "Illuminate\\Database\\DatabaseManager",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Http\\Controllers\\ResourceUpdateController.php",
            "line": 43,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },
        {
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 219,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 176,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 680,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Http\\Middleware\\Authorize.php",
            "line": 18,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\Authorize",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Http\\Middleware\\BootTools.php",
            "line": 20,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\BootTools",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Http\\Middleware\\DispatchServingNovaEvent.php",
            "line": 20,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php",
            "line": 43,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Http\\Middleware\\Authenticate.php",
            "line": 31,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php",
            "line": 75,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php",
            "line": 56,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 682,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 657,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 623,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 612,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 176,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\nova\\src\\Http\\Middleware\\ServeNova.php",
            "line": 26,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\ServeNova",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php",
            "line": 62,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php",
            "line": 29,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Barryvdh\\Cors\\HandlePreflight",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 151,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 116,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\public\\index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "G:\\laravel\\headless\\server.php",
            "line": 21,
            "function": "require_once"
        }
    ]
}`

and I put the log command in line 29, but line 29 was not resolved in my request so no logs

**Comment by mrbuku** [comment]
can you post your composer.json file?

**Comment by jackabox** [comment]
Your installed version of nova is `"laravel/nova": "*",` this will install `dev-master` branch which isn't 2.0.11 and will potentially have active changes on, this is probably what is causing a conflict.

Change `"laravel/nova": "*",` to `"laravel/nova": "^2.0.11",` in your composer.json and run `composer install` and republish assets.

Hope that helps.

**Comment by yassir3wad** [comment]
@jackabox sorry, If you run composer update you will get the latest release. whatever, I was updated my composer.json and I got the same error.

**Comment by jackabox** [comment]
@yassir3wad You will get the **latest stable release unless you have `*`** which is actually pulling in the `dev-master` branch. This is where your issue is, and I believe if you actually tried this change, it would have fixed your issue as was the same issue I had. Unless you have a very specific reason, you shouldn't be referencing `"laravel/nova": "*"` in your composer.json. Please use a stable/tagged version.

In the future, you can double-check your installed version with `composer info` in the terminal. 

However, in the communication of this - Nova 2.1.0 has been released and I don't know about compatibility with flexible-content.

**Comment by Nyratas** [comment]
@jackabox will release an update of flexible-content later today. It will contain a few fixes & new features along with a compatibility check for Nova 2.1.0.

**Comment by jackabox** [comment]
@Nyratas No problem, that should inadvertently fix this issue as well. Hopefully, @yassir3wad can confirm when the new release is out! :)

**Comment by yassir3wad** [comment]
@jackabox I told you that I changed the nova release to 2.0.11 in my composer, and the problem still occurs.

I will check if this issue is solved after the new release.

Thanks.

**Comment by Nyratas** [comment]
Hi @jackabox & @yassir3wad,

We juste released v0.1.10, which is compatible with Nova 2.1.0. Could you check if this issue is still relevant? 

Do not forget to `php artisan nova:publish` & hard-reload (`cmd + shift + R`) Nova in your browser before submitting test data.

**Comment by yassir3wad** [comment]
@Nyratas yeah, It's working, thank you very much

**Comment by slackernrrd** [comment]
I have this same issue with version 0.1.12 and both Nova 2.4.0 and 2.5.0 that was just released. Does something need to be fixed in this module or is there something I can do?

I've published Novas resources with `php artisan nova:publish` but that didn't help.
