### ISSUE TITLE
Validation rules are not applied within Flexible Content

### ISSUE THREAD

**Issue by jesusamezag** [whitecube/nova-flexible-content#6]
Example:

```
Flexible::make('Guías', 'guides')
    ->addLayout('Guía', 'guide', [
        Text::make('No. Guía', 'guide_number')
            ->rules('required')
    ])
```

**Comment by voidgraphics** [comment]
Can confirm, thanks for the heads up!

**Comment by Nyratas** [comment]
Hi @jesusamezag,

Thanks for opening this issue. It is indeed one of the major updates I wanted to publish for this package but never had the time to implement validation earlier.

I took moment to discuss PR #26 with @voidgraphics and we decided not to merge it since it doesn't match our vision on how we would implement this feature.

Instead, I'm currently working on a new release which will add validation on the flexible & contained fields in a much simpler way. I'll try to push it later this week.

**Comment by chrispage1** [comment]
@Nyratas fingers crossed you can. I've just installed this and it's brilliant! Just got to the validation part :(

**Comment by Nyratas** [comment]
Done.

Damn. That was a hard one. But we've got it rollin'!

Of course, this is a new feature for the package, meaning there could be some issues linked to it.   Please open a new, specific and detailed issue if Flexible Content fields validation seems to cause trouble in your project.

**Comment by Nyratas** [comment]
Shipped in [v0.1.8](https://github.com/whitecube/nova-flexible-content/releases/tag/v0.1.8).

**Comment by thebluebug** [comment]
> Applying rules(['required']) on a Flexible Field will now work as expected when no layouts have been added

Aww, man. But... we need to apply rules when there IS a layout...

**Comment by Nyratas** [comment]
Which is also possible. The part you're quoting is from the "bug fixes" part of the release.

The flexible field itself will validate any array-applyable rule. The fields included in the Flexible layouts can receive any rule that would apply if it was used outside the layout.

**Comment by thebluebug** [comment]
@Nyratas Got it, thanks! However, it doesn't work when we wrap a Flexible field with R64 Nova Fields' JSON field (https://github.com/64robots/nova-fields/).

Example code:
```
            JSON::make('Details', [
                Flexible::make('Student Choice Selections', config('magento.gp_bundle_student_choices'))
                    ->button('Add Student Choice Item')
                    ->addLayout('Student Choice Selections', 'student_choice_selections', [
                        Text::make('Choice Description', config('magento.gp_bundle_student_products.selection_title'))
                            ->fieldClasses('choice-description-field px-8 py-6')
                            ->rules('required'),
... 
            ], 'data')->fieldClasses('w-full')
                ->labelClasses('w-1/6 px-8 py-6 hidden')
                ->hideFromIndex(),
```

We get this error: 
`localhost.ERROR: Unable to parse incoming Flexible content, data should be an array. {"userId":2,"exception":"[object] (Exception(code: 0): Unable to parse incoming Flexible content, data should be an array. at /var/www/html/vendor/whitecube/nova-flexible-content/src/Flexible.php:268)`

I know it's expecting an array, but we need our data in JSON format. Is there any workaround?
