### ISSUE TITLE
Bad typehint in TransformFlexibleErrors

### ISSUE THREAD

**Issue by OliverZiegler** [whitecube/nova-flexible-content#67]
When having a `409 Conflict` Error on Nova the progressed Response is not typed as a JsonResponse.

Because of this we get a `Server Error` message instead of the "Another user edited this" message.

The resulting error is:

> Argument 1 passed to Whitecube\NovaFlexibleContent\Http\Middleware\InterceptFlexibleAttributes::transformFlexibleErrors() must be an instance of Illuminate\Http\JsonResponse, instance of Illuminate\Http\Response given

which can be solved by changing the type hint in `TransformFlexibleErrors` line 9 from `JsonResponse` to only `Resonse`.

I assume this can run into new issues with line 22 as `setData` is possibly not available if this is really not an JsonResponse... so there could/should be a type check before!?

**Comment by kaareloun** [comment]
Made a PR with @OliverZiegler suggestion, I just added a check for `get_class($response) === JsonResponse::class`, seems to work but not sure if it could create problems elsewhere

**Comment by Tarpsvo** [comment]
Also running into this issue, did something in Nova change?

**Comment by voidgraphics** [comment]
Hi @Tarpsvo, no, this is due to a recent change in this package that improved compatibility with Advanced Nova Media Library.
