### ISSUE TITLE
Set button type in views to avoid blocking submit of the form by pressing enter

### ISSUE THREAD

**Issue by danielvalchev** [whitecube/nova-flexible-content#69]
Omitting button type in the views causes the browser to activate the first button in the markup rather than the submit button of the form when pressing enter. You have to add `type="button"` on all buttons in the view.

https://github.com/whitecube/nova-flexible-content/blob/ba1e04040f02146b521e95c735fcfe914b780b97/resources/js/components/FormGroup.vue#L4

https://github.com/whitecube/nova-flexible-content/blob/ba1e04040f02146b521e95c735fcfe914b780b97/resources/js/components/FormGroup.vue#L8

https://github.com/whitecube/nova-flexible-content/blob/ba1e04040f02146b521e95c735fcfe914b780b97/resources/js/components/FormGroup.vue#L11

https://github.com/whitecube/nova-flexible-content/blob/ba1e04040f02146b521e95c735fcfe914b780b97/resources/js/components/FormGroup.vue#L14

https://github.com/whitecube/nova-flexible-content/blob/ba1e04040f02146b521e95c735fcfe914b780b97/resources/js/components/FormGroup.vue#L17

https://github.com/whitecube/nova-flexible-content/blob/ba1e04040f02146b521e95c735fcfe914b780b97/resources/js/components/FormGroup.vue#L22

https://github.com/whitecube/nova-flexible-content/blob/ba1e04040f02146b521e95c735fcfe914b780b97/resources/js/components/FormGroup.vue#L23

**Comment by Nyratas** [comment]
Hi @danielvalchev,

A simple Pull Request would be appreciated.

Have a nice day!
