### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by thanoseleftherakos** [whitecube/nova-flexible-content#7]
First of all congratulation for the plugin, amazing work!
Do you have any plans supporting multilingual packages like spatie Nova Translatable?
I've tried it but it's not compatible

Thank you

**Comment by voidgraphics** [comment]
Hello @thanoseleftherakos, thank you for the kind words.

We do plan on having the functionality to include any and every field out there if we can, we're hoping to find a way to make them all work at once.

We would absolutely love a PR that fixes it as well, if anyone feels up to it.

**Comment by Nyratas** [comment]
This issue is valid for every field that stores its values as JSON strings. In fact, it is for example not possible to have a Flexible inside another Flexible at the moment for the exact same reason. Resolving this issue will benefit a lot of other issues with complex fields as well and therefore we'll have to take a look at it soon.

Thanks for bringing this to our attention.

**Comment by InfinityWebMe** [comment]
Good catch but the response of spatie on this subject is categorical : https://github.com/spatie/laravel-translatable/issues/154

**Comment by voidgraphics** [comment]
I think the functionality of Spatie's package is good as is - the plan is to make our package work with theirs, not the opposite 🙂

**Comment by Nyratas** [comment]
Spatie's response would apply if you wanted to use a Flexible field as a "translatable field". In most cases, the translatable fields should only apply to "final" fields, meaning you'll probably have to use the translatable fields inside the Flexible field.

**Comment by Nyratas** [comment]
Alright.

Nested complex fields (= fields that return serializable data) should now be supported as long as they do not `json_encode` their value when filling the _model_ (or layout attributes in our case).

After a few quick tests, nested Flexible fields and Translatable fields (tested with (mrmonat/nova-translatable)[https://github.com/mrmonat/nova-translatable]) are working fine.

A quick note on Translatable fields using [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable) under the hood: you should **not use** the `HasTranslations` trait on your Flexible layouts, which is actually good news. The trait will transform the attribute into a JSON string and as I mentioned earlier, that's something we don't want.

I will publish a release containing these changes (and some other enhancements) right away.

**Comment by thanoseleftherakos** [comment]
Hello,
@Nyratas is this fix on version 0.1.2? 
I've tried it but Im getting "Trying to get property 'layout' of non-object" when I use  mrmonat/nova-translatable

**Comment by Nyratas** [comment]
Hi @thanoseleftherakos,

Yep, this fix was one of the reasons of 0.1.2.
Could you show your setup?

**Comment by JurjenRoels** [comment]
I am trying to get kongulov/nova-tab-translatable working with flexible content.

What I would like to have is to have a tab for each language. The (nested) flexible_content would be part of that tab.

But if I read the above information it is not possible to create that?

I tried the solution in https://github.com/whitecube/nova-flexible-content/issues/44 to add a separate appended field. But still get the $stdClass::Layout error.

**Comment by joeholston** [comment]
Could someone please explain/show an example of making a nested field translatable on a model? My model implements HasTranslations/translatable for other fields, but I am not sure how to denote that 'Heading' inside of a Flexible layout is translatable.

`Flexible::make('About Sections')->addLayout('Text', 'text', [
                Translatable::make('Heading')->singleLine()
            ]),`
