### ISSUE TITLE
Dropdown List Error

### ISSUE THREAD

**Issue by bsormagec** [whitecube/nova-flexible-content#76]
When we add 8 element to list its stay behind of header. Can you add a property to Field make method to set pin top or pin bottom. 
![Screenshot 2019-09-13 12 04 33](https://user-images.githubusercontent.com/965219/64851094-6185ce00-d61f-11e9-9065-d9c7bc6c3045.png)

Thank you.

**Comment by bsormagec** [comment]
@Nyratas  can you check it ?

**Comment by bsormagec** [comment]
@voidgraphics can you check it ?

**Comment by voidgraphics** [comment]
Hi @bsormagec, we hear you. Sorry if it's taking a while, it's not always easy to make time for open source work. We're doing the best we can.

If it is a critical issue for you and can not afford to wait, you are always welcome to open a pull request to add this feature yourself and we'll gladly merge it.

Cheers

**Comment by bsormagec** [comment]
Its ok i can try to look

**Comment by kdrmlhcn** [comment]
This issue will solve with this merge https://github.com/whitecube/nova-flexible-content/pull/116
@voidgraphics @Nyratas @chrisneal

**Comment by Nyratas** [comment]
Thanks @kdrmlhcn ! PR was merged indeed.
