### ISSUE TITLE
Hide / disable reorder arrows

### ISSUE THREAD

**Issue by vayurobins** [whitecube/nova-flexible-content#78]
Hi.
I'm sure it's possible to hide the reorder arrows on the side of the block with CSS, but it would be nice to be able to simply disable them with a method. :-)
![Screenshot 2019-09-19 at 13 18 34](https://user-images.githubusercontent.com/1386354/65239807-0b61d080-dae0-11e9-99d1-d5eed57fac73.png)

**Comment by voidgraphics** [comment]
Should be pretty easy to do if someone wants to submit a PR for this.

**Comment by voidgraphics** [comment]
Hi @vayurobins, I'm thinking about this again and wondering what your use case is? Why wouldn't you allow reordering with the arrows? It seems it would be impossible to enforce a fixed order, since people could just delete layouts and re-add them in a different order if they wanted to.

**Comment by vayurobins** [comment]
Well, I don't need this functionality, since it won't be saved to the database and it will be ordered by date. Each block will be a related resource and not a json string. But I suppose I can to fix this with CSS.

**Comment by Broutard** [comment]
`Flexible::make('Content', 'content')->readonly()`

![image](https://user-images.githubusercontent.com/1552045/102639106-d451f300-4158-11eb-8038-114cfe7461a1.png)

**Comment by handhikadj** [comment]
@Broutard 
that won't insert the values to db. I tested it
