### ISSUE TITLE
Unable to select multiple files

### ISSUE THREAD

**Issue by lilianjin** [whitecube/nova-flexible-content#8]

**Comment by Nyratas** [comment]
Hi @lilianjin,

Can you provide more information about which field you use and how you set up the flexible content ?

**Comment by lilianjin** [comment]
```php
Flexible::make('Images')
    ->addLayout(
        'Images',
        'images',
        [
            Image::make('Image', 'logo'),
            Boolean::make('Main', 'is_main'),
        ]
    )   
```

**Comment by Nyratas** [comment]
Hi @lilianjin,

I just tested your setup and it is working fine for me. However, image fields could not work correctly for several reasons, all not linked to this package:

- Is `APP_URL` correctly configured in your application's `.env` file?
- Are the images you wanted to upload in `storage/app/public/`? If so, you probably just forgot to run `php artisan storage:link`.
- Do you have javascript errors in the browser's console when submitting the form? If your server is not configured for handling uploads you could have a `413` in the console, meaning you should [increase some settings](https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/) before launching uploads.
