### ISSUE TITLE
Not able to be used via non-api solution

### ISSUE THREAD

**Issue by jjmu15** [whitecube/nova-flexible-content#84]
I'm trying to use this with standard blade templating to create re-usable components for the CMS.

Unfortunately it doesn't seem possible because:
- There is no method to return the content in a pre-defined html structure. Adding one similar to in ACF In WordPress which can define the HTML structure (and class names) for each component would be ideal. For example, in pseudo code ... "for each simple content section create a wrapper div with a class of 'simple-content', output the title and content within that div with their own class names' and so on...

Are there any plans to add this feature?

Otherwise thank you very much for creating and sharing such a useful addition to Nova!

**Comment by voidgraphics** [comment]
Good news, you can absolutely do this!

I will refer you to [this section of the readme](https://github.com/whitecube/nova-flexible-content#using-flexible-values-in-views). Once you've followed these instructions, you can loop over the flexible content data like so:

```blade
@foreach($model->flexible as $layout)
    @include('parts.flexible.' . $layout->name())
@endforeach
```

Thank you for the kind words 👍
