### ISSUE TITLE
Cant update required image

### ISSUE THREAD

**Issue by milewski** [whitecube/nova-flexible-content#88]
Hello Having something like this works on create but fails on the update, the only way to bypass it is by either removing the required rule or re-selecting the image every time want to update...

```php
Flexible::make(__('Content'), 'content')
                    ->addLayout(__('Panel'), 'panel', [
                        Text::make(__('Title'), 'title'),
                        Image::make(__('Icon'), 'Icon')->rules('required'),
                    ])
```

![image](https://user-images.githubusercontent.com/2874967/65768723-5628bb80-e164-11e9-8b25-f68e8ceb5c2e.png)

**Comment by voidgraphics** [comment]
Hi @milewski which version of nova-flexible-content are you using?

**Comment by milewski** [comment]
Nova `2.3.1`, 
nova-flexible-content: `0.1.12`

**Comment by voidgraphics** [comment]
Is this not related to https://github.com/laravel/nova-issues/issues/885 ?

**Comment by milewski** [comment]
@voidgraphics just tried! it also happens without any Flexible... so this is a bug with nova itself

**Comment by voidgraphics** [comment]
It does look like a bug - however in the responses to that issue, it seems it's like that by design. There is a solution somewhere in there that should work.
