### ISSUE TITLE
Image not working on nested flexible content

### ISSUE THREAD

**Issue by jackabox** [whitecube/nova-flexible-content#9]
Trying to upload an image to a nested flexible field content and the image will not process.

**Comment by voidgraphics** [comment]
Are you getting an error message? Image fields seem to work fine when we use them.

Maybe take a look [here](https://github.com/whitecube/nova-flexible-content/issues/8#issuecomment-470936669).

**Comment by jackabox** [comment]
Normal images are fine, I'm referring to when they are nested. I have a Flexbile field inside a Flexbile field and the image upload here does not process the image. 

No error is shown or logged.

![Screenshot 2019-03-11 at 09 58 50](https://user-images.githubusercontent.com/3618433/54115476-69e91c00-43e4-11e9-9e79-c6073a3c98a5.png)

**Comment by voidgraphics** [comment]
Thanks for the clarification, we will look into it asap.

**Comment by drobee** [comment]
Do you have any workaround to this? I'm trying to create a gallery field where all the images are nested image fields.

**Comment by casberkman1** [comment]
I have the same problem

**Comment by jackabox** [comment]
@drobee no workaround that I know yet. Hoping @voidgraphics or team can get an update for this as the package is awesome otherwise.

**Comment by voidgraphics** [comment]
@jackabox I will do my best to take a look at this today and hopefully have a fix for you guys.

**Comment by Nyratas** [comment]
Good news!

We just sat together with @voidgraphics in order to close this issue. It is shipped in the latest release ([v0.1.3](https://github.com/whitecube/nova-flexible-content/releases/tag/v0.1.3)). Can you confirm it fixes your use cases? Thank you!

**Comment by jackabox** [comment]
Seems to have fixed everything up - many thanks! :)

**Comment by emilaspman** [comment]
I updated to 0.1.3 and now image upload works for nested flexible content. But if I update another field after uploading and saving images, they disappear. 

![Screenshot 2019-04-04 at 20 06 58](https://user-images.githubusercontent.com/2176948/55578310-e2a67400-5715-11e9-9c52-9e02db0324c3.png)

**Comment by Nyratas** [comment]
Hi @emilaspman,

Good point. I will check this right away.

**Comment by Nyratas** [comment]
Should be solved in the latest release ([v0.1.4](https://github.com/whitecube/nova-flexible-content/releases/tag/v0.1.4)). Can you confirm?

Thank you!

**Comment by emilaspman** [comment]
Confirmed. I can now update other fields without images disappearing. 

Thanks for this amazing plugin!

**Comment by dimon-camelot** [comment]
The same problem v1.0.12

**Comment by tmartty** [comment]
I can confirm the problem has returned with v1.0.12

Any workaround or possible fix?
