### ISSUE TITLE
File field does not work properly

### ISSUE THREAD

**Issue by vayurobins** [whitecube/nova-flexible-content#92]
Hi.
I've been trying to get the File field to work in my Flexible layout, but it's not working as hoped.
It's possible to attach a file when creating a block. However, if the user does not attach a file the first time, but then edits the block and tries to attach a file, it will not save the file to the database.
Also, it is not possible to delete a file.
<img width="746" alt="Screenshot 2019-10-05 at 16 53 29" src="https://user-images.githubusercontent.com/1386354/66262200-b20cc900-e790-11e9-9915-28c7a94716c2.png">

**Comment by vayurobins** [comment]
Does anybody have any suggestions on how one could add a file field that works? I have tried with built-in File field, and I have also tried with Laravel Advanced Nova Media Library. Neither will work. Any suggestions would be appreciated. :-)

**Comment by vayurobins** [comment]
Is there any way that I could pay someone to fix this issue? I am really stuck on this problem and my project has been halted because of it. We need this to be fixed. What would it cost for someone to fix this?
Also this one #83 would be amazing if fixed.

**Comment by Nyratas** [comment]
Hi @vayurobins,

Sorry for the delay, we're quite busy these days on other projects. First of all, for the "delete" behavior, there is an open PR (#73) tackling the problem right now. It is not as simple as it seems and I hope we'll have positive results soon.

Regarding the blocking issue you're having, I'm willing to debug it with @voidgraphics in priority. Could you please contact us at hello@whitecube.be in order to discuss modalities for our intervention? Thanks!

**Comment by wize-wiz** [comment]
@vayurobins @Nyratas What is the status here?

**Comment by vayurobins** [comment]
I ended up using the extension Filepond https://novapackages.com/packages/digital-creative/nova-filepond, which works great.

**Comment by wize-wiz** [comment]
@vayurobins Do you mean it works in combination with the Flexible Content package. 

So no one here agreed on anything trying to solve this problem?

**Comment by vayurobins** [comment]
Yes, with Flexible Content it works great. No, we did not agree on getting this developed. I think it is added to the Todo list when @Nyratas finds time to fix it, but this will have to be confirmed with @Nyratas

**Comment by Nyratas** [comment]
Indeed, we're currently crumbling under a lot of work and did not have the time to give it all a closer look. Sorry!

I hope we'll be able to give it some attention soon, since we're encountering some of the listed issues ourselves since the latest versions of Nova.
