### ISSUE TITLE
Unnecessary spacing so text is no longer aligned

### ISSUE THREAD

**Issue by tpetry** [whitecube/nova-flexible-content#97]
When displaying of titles is disabled there is always a small padding at the top of the very first element which makes the text not being aligned anymore:
<img width="595" alt="Bildschirmfoto 2019-10-17 um 16 53 11" src="https://user-images.githubusercontent.com/315686/67021209-9a720080-f0ff-11e9-9f31-b97853751183.png">

The same is happening for flexible content fields at the bottom, the last element of the last layout is adding more padding to the bottom than all other nova fields. Its just not the same and hard to notice ;)

**Comment by Nyratas** [comment]
Hi @tpetry,

Thanks for noticing. I think the padding system has been updated in Nova 2.5.0.
I'm a little bit busy for the moment, so feel free to suggest a PR with the needed changes, it shouldn't be too hard. :)

Have a great day!

**Comment by Nyratas** [comment]
This is issue seems to be fixed in the latest version of the package.
