### ISSUE TITLE
Unable to parse incoming Flexible content, data should be an array.

### ISSUE THREAD

**Issue by slackernrrd** [whitecube/nova-flexible-content#99]
I get `Unable to parse incoming Flexible content, data should be an array.` when trying to save a resource that has a Flexible field, using Nova 2.5.0 (also 2.4.0, not sure about earlier releases) and nova-flexible-content 0.1.12.

I tracked down the cause of the error to being that FieldServiceProvider::boot() being run before NovaCoreServiceProvider::boot(). The first method calls

```
$this->app['router']->pushMiddlewareToGroup('nova', InterceptFlexibleAttributes::class);
```

while the second method calls

```
Route::middlewareGroup('nova', config('nova.middleware', []));
```

which overwrites all the middleware in the group.

The order in which the providers get booted seems random-ish, and I dont really know of a good way to get them to run in a specific order (other than disabling auto-discovery for them, and adding them manually to the provider list in `config/app.php`).

I solved this issue for my app by adding `InterceptFlexibleAttributes::class` to the middleware key of `config/nova.php`, but I'm probably not the only one running into this(?) so it would be nice to have a zero-config solution.

To minimize the need of configuration, one solution might be to check if the `nova` middleware group exists before pushing to it. If it doesn't, it could be possible to instead add the middleware to the `nova.middleware` config key programatically (using `$this->app['config']->set()`) which should have the same effect as adding it manually to the config file.

**Comment by Nyratas** [comment]
Hi @slackernrrd,

Thanks for reporting this issue and narrowing it down. I'll make some time this friday afternoon and try to solve it based on your observations.

Have a good night !

**Comment by slackernrrd** [comment]
I had to try it, and my theory seemed to work :)
